added explaining document + pictures wireframes
Schmiddl99/experimenteverwaltung-i2 pull request #110
Opened 2021-01-14 13:30 UTC by AlenaBischoff

added all the made wireframes and an bigger document explaining them; for later comparing or to show our mentor.

closes #105

2021-01-14 15:00 UTC, Schmiddl99 approved these changes
Sieht gut aus. Hast mein OK, auch wenn ich die Bildchen jetzt nicht anschauen konnte.

2021-01-14 15:07 UTC, Schmiddl99 requested changes
Zur Buchungsbestätigung: evtl. Button mit "zum Journal" hinzufügen?

2021-01-14 15:26 UTC, Greyhound993 requested changes

2021-01-14 15:26 UTC, Greyhound993 commented on Dokumentationen/requirements/wireframes/WF_overview.adoc
> +
bitte noch Bilder Ordner hinzufügen
:imagesdir: wf_pictures

dann sollte es hoffentlich gehen

2021-01-14 15:46 UTC, Greyhound993 reviewed
> Zur Buchungsbestätigung: evtl. Button mit "zum Journal" hinzufügen?

Bitte jetzt nichts mehr ändern, da wir jetzt dringen mal irgendwas abschließen müssen :)

2021-01-14 15:46 UTC, Greyhound993 commented on Dokumentationen/requirements/wireframes/WF_overview.adoc
> +
image: Name.PNG [Bla bla]

hoffe dann geht es 
Natürlich überall :)

2021-01-14 18:02 UTC, AlenaBischoff commented
@Greyhound993 
@Schmiddl99 

Changes eingefügt und gepusht. Hoffe jetz passt es

2021-01-14 19:41 UTC, Greyhound993 requested changes
Jetzt werden die Bilder angezeigt. Alles toll

2021-01-14 19:42 UTC, Greyhound993 approved these changes
Jetzt werden die Bilder angezeigt. Alles toll

2021-01-17 13:57 UTC, Schmiddl99 approved these changes

2021-01-17 13:57 UTC, merged