created UC: Dozentendozentenwoche
Schmiddl99/experimenteverwaltung-i2 pull request #111
Opened 2021-01-14 14:55 UTC by Schmiddl99

added new UC and updated UC-Model (added prioritization)

refs #92

2021-01-14 15:01 UTC, Schmiddl99 commented
Keine Sorge, ich habe den UC nicht so genannt ^^

2021-01-15 16:35 UTC, s80523 commented
"UC “Dozentenwoche ansehen und Drucken” muss zergliedert werden! 

-> UC Dozentenwoche abfragen 
-> UC Druckansicht anzeigen 
-> Erweiterungs-UC Druckansicht drucken (textuell strg+p beschreiben; “Nutze Browserfunktion zum Drucken”) "

2021-01-15 16:37 UTC, s80523 requested changes
'UC “Dozentenwoche ansehen und Drucken” muss zergliedert werden!

-> UC Dozentenwoche abfragen
-> UC Druckansicht anzeigen
-> Erweiterungs-UC Druckansicht drucken (textuell strg+p beschreiben; “Nutze Browserfunktion zum Drucken”) '

2021-01-16 15:40 UTC, Schmiddl99 commented
@s80523 Bitte nochmal reviewen

2021-01-16 16:22 UTC, s80523 requested changes
Die zwei Kleinigkeiten müssen noch behoben werden, sonst habe ich nichts auszusetzen.

2021-01-16 16:22 UTC, s80523 commented on Dokumentationen/requirements/use_case_07.inc.adoc
> +--- keine Nachbedingungen ---
Hier muss es "keine besonderen Anforderungen" heißen.

2021-01-16 16:22 UTC, s80523 commented on Dokumentationen/requirements/use_case_06.inc.adoc
> +--- keine Nachbedingungen ---
Hier muss es "keine besonderen Anforderungen" heißen.

2021-01-16 16:49 UTC, Greyhound993 approved these changes
Finde gut so, danke für die schnelle Arbeit

2021-01-19 15:12 UTC, Schmiddl99 commented on Dokumentationen/requirements/use_case_07.inc.adoc
> +--- keine Nachbedingungen ---
done

2021-01-19 15:14 UTC, merged