rolls update
Schmiddl99/experimenteverwaltung-i2 pull request #112
Opened 2021-01-14 16:25 UTC by Greyhound993

Rollen wurden angepasst und Stakeholder entfernt

refs #78

2021-01-18 13:43 UTC, TobiasK20 requested changes
Gern bei mir noch ESSENCE-Navigator als Verantwortlichkeit
Bei Gregor Redeführer in Meetings SEI
Frau Prof. Krawietz als Stakeholder (Anwenderin) bitte mit aufnehmen (Physik-Professorin, Vorlesungen für WIng und BauIng)

2021-01-18 13:43 UTC, TobiasK20 commented on Dokumentationen/project_management/Rollenübersicht.adoc
> +GitHup Verantwortlicher (zus.)
GitHub bitte mit b am Ende ;)

2021-01-18 13:43 UTC, TobiasK20 commented on Dokumentationen/project_management/Rollenübersicht.adoc
> -|Git-Hup-Verantwortlicher
RF

2021-01-18 13:43 UTC, TobiasK20 commented on Dokumentationen/project_management/Rollenübersicht.adoc
> +|GitHup-Kontrolleur
RF

2021-01-20 15:09 UTC, s80523 reviewed
Von meiner Seite aus gibt es hier nichts mehr zu ergänzen. Vielleicht noch die erwähnten Punkte vom Tobias umsetzen aber sonst passt alles soweit, denke ich.

2021-01-20 23:41 UTC, merged