gregor_add_survey
Schmiddl99/experimenteverwaltung-i2 pull request #119
Opened 2021-01-18 12:54 UTC by Greyhound993

Bitte mal anschauen ob wir das so verwenden können
und ich habe es auch einfach mal zur Dokumenation dazu
weil ich nicht wusste wohin :D

2021-01-18 20:52 UTC, TobiasK20 requested changes

2021-01-18 20:52 UTC, TobiasK20 commented on Dokumentationen/requirements/survey_for_essence.adoc
> +
RF: arithmetisches

2021-01-18 20:52 UTC, TobiasK20 commented on Dokumentationen/requirements/survey_for_essence.adoc
> +Diese Umfrage war für alle Gruppenmitglieder verpflichtend und anonym, sie wurde mit Hilfe von Microsoft Teams durchgeführt.
Kannst ja ggf. noch Polly erwähnen

2021-01-18 20:52 UTC, TobiasK20 commented on Dokumentationen/requirements/survey_for_essence.adoc
> +
Vlt noch eine kurze Erläuterung, in welchem Zeitraum und aus welchem Anlass die Umfrage durchgeführt wurde?

2021-01-19 09:42 UTC, TobiasK20 approved these changes

2021-01-19 16:14 UTC, timwuerzburg approved these changes

2021-01-19 20:25 UTC, merged