ESSENCE Screenshot + testweise Verlinkungen
Schmiddl99/experimenteverwaltung-i2 pull request #121
Opened 2021-01-18 21:07 UTC by TobiasK20

refs #69

2021-01-18 21:07 UTC, TobiasK20 commented
Bitte bestätigen, möchte die Verlinkungen testen

2021-01-18 21:12 UTC, Greyhound993 requested changes

2021-01-18 21:12 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +image::31.12.20_END_I2.png[ALPHA states 05.01.2020]
Bild wird nicht angezeigt

2021-01-18 21:12 UTC, Greyhound993 commented on Dokumentationen/project_management/project_plan.adoc
> +xref:Rollenübersicht.adoc#Verantwortlichkeiten[Rollenübersicht]
Der Link funktioniert

2021-01-20 17:58 UTC, TobiasK20 commented
In Visual studio wird es jetzt angezeigt, wenn ich die pdf generiere auch. Nur auf Github/Browser nicht. Schließe den PR damit.

2021-01-20 17:58 UTC, merged