some grammar corrections
Schmiddl99/experimenteverwaltung-i2 pull request #129
Opened 2021-01-21 17:34 UTC by Schmiddl99

refs #75

2021-01-21 17:39 UTC, Schmiddl99 commented
some grammar corrections

2021-01-22 12:38 UTC, Greyhound993 approved these changes

2021-01-22 14:58 UTC, richardboehme requested changes
Mir ist noch ein kleiner Schreibfehler aufgefallen der sich irgendwie eingeschlichen hat

2021-01-22 14:58 UTC, richardboehme commented on Dokumentationen/test/test_cases.adoc
> +a| * der Button "Buchung abschließen" ist bis zur Auswahl mindestens eines Experments ausgegraut und kann nicht geklickt werden.
Hier ist irgendwie ein Schreibfehler wieder rein gekommen oder?

```suggestion
a| * der Button "Buchung abschließen" ist bis zur Auswahl mindestens eines Experiments ausgegraut und kann nicht geklickt werden. 
```

2021-01-25 16:46 UTC, merged

2021-01-25 16:46 UTC, Schmiddl99 commented
merged