145_gregor_add_TC_15-18
Schmiddl99/experimenteverwaltung-i2 pull request #170
Opened 2021-01-28 12:02 UTC by Greyhound993

add the tcs

refs #145

 Soll der TC 18 vielleicht raus, weil im Journal soll es ja pro Buchung einen Papierkorb und einen Stift geben. Das wären doch redundante Schaltflächen oder ?

2021-01-28 12:23 UTC, richardboehme commented
> Soll der TC 18 vielleicht raus, weil im Journal soll es ja pro Buchung einen Papierkorb und einen Stift geben. Das wären doch redundante Schaltflächen oder ?

Nein. Genau genommen sind es zwei verschiedene Funktionen. Zum Beispiel führt die eine Schaltfläche zum Bearbeiten von Buchung A und die andere Schaltfläche zum Bearbeiten der Buchung B. Die Funktion ist also nicht komplett identisch.

2021-01-28 13:28 UTC, Schmiddl99 requested changes
mMn muss nur die Formulierung angepasst werden. 👌

2021-01-28 13:28 UTC, Schmiddl99 commented on Dokumentationen/test/test_cases.adoc
> +a| * Admin ist angemeldet
```suggestion
a| * ein Admin ist mit validen Zugangsdaten angemeldet
```
Damit es einheitlich ist. Außerdem kann es auch sein, dass noch iwann ein neuer Admin dazukommt.

2021-01-28 16:57 UTC, s80523 requested changes

2021-01-28 16:57 UTC, s80523 commented on Dokumentationen/test/test_cases.adoc
> +|*Beschreibung* |Es muss sichergestellt werden, dass der Admin keinen Zugriff auf das Dozenten-Journal hat, die Dozenten nur ihr persönliches Journal einsehen dürfen und nur der Admin die Statistik a
Evtl. nicht in der "muss" Form, weil das nach einer Anforderung klingt. "Es wird erwartet" wurde bis jetzt bei den restlichen TCs verwendet.

2021-01-28 16:57 UTC, s80523 commented on Dokumentationen/test/test_cases.adoc
> +a| * Admin ist angemeldet
\+
Das "valide" würde ich aber weglassen, das ist eigentlich schon durch andern TCs abgedeckt - sprich: man kann sich nicht mit invaliden Daten anmelden

2021-01-28 16:57 UTC, s80523 commented on Dokumentationen/test/test_cases.adoc
> -a| *
evlt. in der Vergangenheit schreiben. Das spielt zwar sicherlich keine große Rolle, würde aber für den letzten Touch Einheitlichkeit sorgen. :D

2021-01-28 16:57 UTC, s80523 commented on Dokumentationen/test/test_cases.adoc
> +|*Beschreibung* |Nach einem Internetausfall müssen die Anwenderdaten noch abrufbar sein.
hier ging es glaube ich nicht um den Netzausfall, sondern um einen Neustart, nach dem alle Buchungs- und Anwenderdaten noch da sind.

2021-01-28 16:57 UTC, s80523 commented on Dokumentationen/test/test_cases.adoc
> +|*Beschreibung* |Es darf zu keinem Zeitpunkt Schaltflächen geben, die denselben Zweck erfüllen oder dieselbe Funktion aufrufen.
das ist wieder eine Anforderung. -> "erwartet wird" wäre mMn besser

2021-01-28 19:32 UTC, richardboehme requested changes
Sieht soweit gut aus! Einen kleinen RF hatte ich noch gefunden und eine inhaltliche Frage habe ich noch ergänzt.

2021-01-28 19:32 UTC, richardboehme commented on Dokumentationen/test/test_cases.adoc
> +* Dozent kann die Statistik nicht aufrufen
Hier fehlt glaube ich noch der Bezug zu der Dozentenwoche oder?

2021-01-28 19:32 UTC, richardboehme commented on Dokumentationen/test/test_cases.adoc
> +* es muss ein Dozentenkonto geben
Wozu brauchen wir die beiden Konten? Oder sind das die Daten die wir hier auf Persistenz testen wollen? Wenn ja: wollen wir (um dem Titel des TC nachzukommen) auch eine Buchung zu den benötigten Daten hinzufügen?

2021-01-28 19:32 UTC, richardboehme commented on Dokumentationen/test/test_cases.adoc
> +* es existiert mindest eine Buchung
```suggestion
* es existiert mindestens eine Buchung
```

2021-02-01 16:30 UTC, richardboehme approved these changes

2021-02-03 19:12 UTC, merged