Add files via upload
Schmiddl99/experimenteverwaltung-i2 pull request #172
Opened 2021-01-28 13:41 UTC by timwuerzburg

2021-01-29 20:59 UTC, Greyhound993 approved these changes
Schaut gut aus, hab keine RF gefunden, und die Sonderzeichen werden bei mir dargestellt.

2021-01-30 08:02 UTC, TobiasK20 requested changes

2021-01-30 08:02 UTC, TobiasK20 commented on Dokumentationen/project_management/Risk_List_neu2.csv
> +7;27.01.2021;Übersehen von Anforderungen;Durch ein nicht rechtzeitiges einbeziehen aller Stakeholder, kann es zum übersehen von Anforderungen kommen. Dies kann zur Folge haben, dass ein erhöhter Mehr
RF: Übersehen groß schreiben

2021-01-30 08:02 UTC, TobiasK20 commented on Dokumentationen/project_management/Risk_List_neu2.csv
> +7;27.01.2021;Übersehen von Anforderungen;Durch ein nicht rechtzeitiges einbeziehen aller Stakeholder, kann es zum übersehen von Anforderungen kommen. Dies kann zur Folge haben, dass ein erhöhter Mehr
Ebenso Einbeziehen

2021-01-30 08:02 UTC, TobiasK20 commented on Dokumentationen/project_management/Risk_List_neu2.csv
> +7;27.01.2021;Übersehen von Anforderungen;Durch ein nicht rechtzeitiges einbeziehen aller Stakeholder, kann es zum übersehen von Anforderungen kommen. Dies kann zur Folge haben, dass ein erhöhter Mehr
bei verschoben fehlt ein v

2021-01-30 08:02 UTC, TobiasK20 commented on Dokumentationen/project_management/Risk_List_neu2.csv
> +7;27.01.2021;Übersehen von Anforderungen;Durch ein nicht rechtzeitiges einbeziehen aller Stakeholder, kann es zum übersehen von Anforderungen kommen. Dies kann zur Folge haben, dass ein erhöhter Mehr
Krawietz ist falsch geschrieben

2021-02-05 20:47 UTC, TobiasK20 approved these changes

2021-02-07 20:49 UTC, merged