add test cases 23 to 26
Schmiddl99/experimenteverwaltung-i2 pull request #173
Opened 2021-01-28 19:21 UTC by richardboehme

War mir hier vor allem bei den Nachbedingungen zu TC 24 und 25 unsicher (vielleicht gibt es da eine schönere Formulierung?)

closes #145

2021-01-30 16:49 UTC, Schmiddl99 requested changes
Dem Code nach ist alles korrekt formatiert, allerdings in der "View"-Ansicht, steht derzweite Use Case mit unter der Überschrift deines Dritten. wenn das nur ein Anzeigefehler ist, dann siehe den Kommentar als approval.

2021-01-30 16:52 UTC, Schmiddl99 commented
> War mir hier vor allem bei den Nachbedingungen zu TC 24 und 25 unsicher (vielleicht gibt es da eine schönere Formulierung?)

Nicht schön, aber selten. Nein, Spaß. Mir fallen aber auch keine wirklich besseren Nachbedingungen ein. Vielleicht könnte man halt das "wie erwartet" durch genaue Aussagen, wie bspw.: "Während des gesamten Testvorgangs sind keine Pop-Ups für Eingabemöglichkeiten erschienen." Aber vllt ist das auch etwas unspezifisch.

2021-01-31 17:13 UTC, s80523 approved these changes
Von mir aus gibts soweit eigentlich nichts zu bemängeln. Ich werde das "manueller Test" bei mir mit in den Titel verschieben. 
Eine Kleinigkeit: hatten wir nicht gesagt, dass wir das "valide" bei den Daten etc. weglassen, weil das eig. doppelt gemoppelt ist, da ja invalide Voreinstellungen etc. gar nicht getätigt werden können?

2021-01-31 17:36 UTC, richardboehme commented
> Von mir aus gibts soweit eigentlich nichts zu bemängeln. Ich werde das "manueller Test" bei mir mit in den Titel verschieben.
> Eine Kleinigkeit: hatten wir nicht gesagt, dass wir das "valide" bei den Daten etc. weglassen, weil das eig. doppelt gemoppelt ist, da ja invalide Voreinstellungen etc. gar nicht getätigt werden können?

Aber wir haben doch im Moment überall sowas stehen wie "es wurde valide Daten in die Voreinstellungen eingegeben" oder "ein Dozent ist mit validen Zugangsdaten angemeldet"?

2021-02-01 15:02 UTC, Greyhound993 approved these changes
Ich find es gut, keine RF gefunden,

2021-02-01 15:04 UTC, Greyhound993 commented
> > Von mir aus gibts soweit eigentlich nichts zu bemängeln. Ich werde das "manueller Test" bei mir mit in den Titel verschieben.
> > Eine Kleinigkeit: hatten wir nicht gesagt, dass wir das "valide" bei den Daten etc. weglassen, weil das eig. doppelt gemoppelt ist, da ja invalide Voreinstellungen etc. gar nicht getätigt werden können?
> 
> Aber wir haben doch im Moment überall sowas stehen wie "es wurde valide Daten in die Voreinstellungen eingegeben" oder "ein Dozent ist mit validen Zugangsdaten angemeldet"?

Ich hätte auch gesagt wir lassen valide stehen weil doppelt ist besser als einmal zu wenig :D

2021-02-02 15:48 UTC, merged