147 tobias adjust vision zukunftsvision
Schmiddl99/experimenteverwaltung-i2 pull request #177
Opened 2021-01-31 11:24 UTC by TobiasK20

2021-01-31 11:25 UTC, TobiasK20 commented
Verlinkungen funktionieren noch nicht, kann auch noch nicht nachvollzogen werden

2021-02-01 14:48 UTC, Greyhound993 requested changes

2021-02-01 14:48 UTC, Greyhound993 commented on Dokumentationen/requirements/vision.adoc
> +* **Kopierfunktion:** Eine Kopierfunktion zur Reproduktion aller Buchungen eines vergangenen Semesters wurde gewünscht. Wir sahen hier einen Zielkonflikt und einigten uns mit allen Stakeholdern darau
doppelte **
Hier muss noch der . entfernt werden

2021-02-01 14:48 UTC, Greyhound993 commented on Dokumentationen/requirements/vision.adoc
> +|Agreement (Stand: 07.01.2021)|	Probleme, die zu adressieren
Wort vergessen: Probleme, .... SIND

2021-02-01 14:48 UTC, Greyhound993 commented on Dokumentationen/requirements/vision.adoc
> +* Die Kopierfunktion entspringt der **grundsätzlichen Motivation** des Projektes: Den Dozenten soll die **Arbeit im höchstmöglichen Umfang vereinfacht werden**. Deshalb soll der einmal bestrittene Ab
2x doppelt **
Hier muss noch der . entfernt werden

2021-02-01 14:48 UTC, Greyhound993 commented on Dokumentationen/requirements/vision.adoc
> +* Dozent muss sich **seine** Woche drucken können -> braucht auch Zugang zu SEINER Dozentenwoche (Journal als Historie, Dozentenwochen aber auch)
doppelte **

2021-02-05 19:20 UTC, TobiasK20 commented on Dokumentationen/requirements/vision.adoc
> +|Agreement (Stand: 07.01.2021)|	Probleme, die zu adressieren
Durchaus beabsichtigt ;)

2021-02-06 02:28 UTC, Greyhound993 commented on Dokumentationen/requirements/vision.adoc
> +|Agreement (Stand: 07.01.2021)|	Probleme, die zu adressieren
Okay ich steh gerade auf dem Schlauch :D 
da soll wirklich stehen: Probleme, die zu adressieren             und NICHT : 
Probleme, die zu adressieren SIND 
???? :D

2021-02-06 10:18 UTC, TobiasK20 commented on Dokumentationen/requirements/vision.adoc
> +|Agreement (Stand: 07.01.2021)|	Probleme, die zu adressieren
Das darf man grammatikalisch so sagen. Aber gut. Hab es jetzt geändert damit alle zufrieden sind ;)
 PR ok?

2021-02-06 10:21 UTC, Greyhound993 approved these changes

2021-02-06 10:21 UTC, merged