Corrected and reviewed the Iteration Plans 2+3
Schmiddl99/experimenteverwaltung-i2 pull request #180
Opened 2021-02-01 13:41 UTC by Schmiddl99

look for annotations in ticket #160

refers #160

2021-02-01 14:41 UTC, Greyhound993 requested changes

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* erreichen der Bestätigung der Vision durch den Kunden; Über die initialen Anforderungen herrscht Einigkeit.
Hier muss noch der . entfernt werden

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* **Wissensaustausch:** Interessierte Mitglieder sollen ein GitHub-Tutorial erhalten, was einerseits die Arbeit im Team fördert anderseits auch einen weiteren Mehrwert innerhalb dieses Moduls schafft
Hier muss noch der . entfernt werden
hier doppelte ** sollten nicht einfache reichen ? Also * bla * ?

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* 6 Use Cases wurden dokumentiert und in einem Modell zusammengefasst (Doku liegt als ADOC vor)
hier 6x Hier muss noch der . entfernt werden

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +** **Understand what to build:** Grundsätzlich verstanden. *Erfolgskriterien* sind noch nicht zu 100% klar - z.B. Ablaufplan des Buchens. Journal wurde angenommen. *Konfliktpunkt* ist die Kopierfunkt
doppel *

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +** *Determine at least one possible solution:* Die Vision ist technisch umsetzbar.
Hier muss noch der . entfernt werden

2021-02-01 14:41 UTC, Greyhound993 commented on Dokumentationen/project_management/iteration_plan_03.adoc
Zeile 166    ! vielleicht raus ...

2021-02-05 12:40 UTC, Greyhound993 approved these changes

2021-02-05 20:16 UTC, TobiasK20 approved these changes

2021-02-06 07:27 UTC, timwuerzburg approved these changes

2021-02-06 13:40 UTC, Greyhound993 approved these changes

2021-02-06 21:35 UTC, TobiasK20 commented
Wer hat denn Version statt Vision, Interception Phase statt Inception und so einen bull*** geschrieben? Das war alles schon so richtig!!!! :D

2021-02-06 21:41 UTC, TobiasK20 commented
@timwuerzburg Was ist im IP3 mit den ganzen Fragezeichen? Das müsste langsam mal vervollständigt werden! -> Bitte schnellstmöglich beheben. Bei konkreten Fragen gern anschreiben.

2021-02-07 10:37 UTC, timwuerzburg approved these changes

2021-02-08 14:34 UTC, merged