added all the qm documents
Schmiddl99/experimenteverwaltung-i2 pull request #181
Opened 2021-02-01 14:00 UTC by AlenaBischoff

closes #151

2021-02-01 14:01 UTC, AlenaBischoff commented
Teilweise noch nicht fertig, weiß an einer Stelle nicht so ganz was ich schreiben soll. Bitte um Hilfe :)

2021-02-01 18:16 UTC, TobiasK20 requested changes
Mir gefällt die Strukturierung der Regeln sehr gut! :)

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +
Den Satz mit dem Feedback bitte nochmal überdenken :) (Formulierung holprig)

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +Diesen unnötig langen Besprechungen wollten wir entgegenwirken. Deshalb entschieden wir uns, einen Redeführer / Meeting Leiter einzusetzen. Dieser gab uns vorab die Themen als Liste, mit der ungefähr
Würde Meeting-Leiter streichen, war ja klar als Redeführer benannt

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +Wichtig ist, dass im Team offen und ehrlich miteinander diskutiert werden kann. Hierbei sollen Rollen (bspw. Teamleiter, Developer…) außer Acht gelassen werden und auf einer gemeinsamen Ebene, nämlic
...von Teammitglied zu Teammitglied,...

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +Verantwortung bedeutet die Übernahme von schlechten sowie guten Ergebnissen einzugestehen und zu tragen. Wichtig ist hier, dass bei negativem Auftreten niemals jemanden die Schuld gegeben werden soll
bei negativem Auftreten klingt hier komisch :D

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +* Meetingführer bestimmen
Würde "Redeführer" wieder verwenden

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +* Redner gibt immer an Teilnehmer seiner Wahl weiter → Aufmerksamkeit steigern
+ letzte Person, die den Raum betritt, muss beginnen :)

2021-02-01 18:16 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +Ziel ist es, alle Beteiligten auf denselben Wissensstand über die angefallenen Aufgaben zu bringen, eventuell Lasten umverteilen oder Blocker aus dem Weg schaffen.
"zu" fehlt 2x

2021-02-05 08:58 UTC, AlenaBischoff commented
@s80534 @TobiasK20 
Bitte erneut checken, ob jetzt alles so passt :) würde das gerne zum Abschluss bringen :)

2021-02-05 20:24 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +
Bitte Rückmeldung ob berücksichtigt! (sie und Personen würde ich immer noch tauschen)

2021-02-05 20:24 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_rules.adoc
> +Verantwortung bedeutet die Übernahme von schlechten sowie guten Ergebnissen einzugestehen und zu tragen. Wichtig ist hier, dass bei negativem Auftreten niemals jemanden die Schuld gegeben werden soll
Würde z.B. schreiben "Wichtig ist hier, dass bei Problemen niemand auf persönlicher Ebene beschuldigt wird"

2021-02-05 20:24 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +Diesen unnötig langen Besprechungen wollten wir entgegenwirken. Deshalb entschieden wir uns, einen Redeführer / Meeting Leiter einzusetzen. Dieser gab uns vorab die Themen als Liste, mit der ungefähr
Yes/No?

2021-02-05 21:15 UTC, AlenaBischoff commented on Dokumentationen/project_management/qm/qm_review.adoc
> +
Eigetlich Hab ich das berücksichtig... Könntest du vielleicht nen Vorschlag machen wie du es besser fändest???

2021-02-05 21:38 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +
"...Feedback, ob sie..." -> "...Feedback, inwieweit Änderungen und Bestimmungen [durch einzelne Teammitglieder] angenommen wurden..." (Vorschlag)

2021-02-05 21:40 UTC, TobiasK20 commented on Dokumentationen/project_management/qm/qm_review.adoc
> +
"...Feedback, ob sie..." -> "Feedback, wie die Änderungen und Bestimmungen [durch einzelne Teammitglieder] angenommen wurden..." (Vorschlag)

2021-02-05 22:05 UTC, AlenaBischoff commented on Dokumentationen/project_management/qm/qm_review.adoc
> +Diesen unnötig langen Besprechungen wollten wir entgegenwirken. Deshalb entschieden wir uns, einen Redeführer / Meeting Leiter einzusetzen. Dieser gab uns vorab die Themen als Liste, mit der ungefähr
was zum fick, ich hatte das alles schon abgeändert o.o ich hatte aber irgendwie probleme mit dem pushen... ich änder das nochmal!

2021-02-06 10:45 UTC, TobiasK20 approved these changes

2021-02-06 10:47 UTC, merged