Corrected and Reviewed the Test Cases
Schmiddl99/experimenteverwaltung-i2 pull request #186
Opened 2021-02-03 20:06 UTC by Schmiddl99

nur ein bisschen Orthographie

refers #150

2021-02-05 08:47 UTC, AlenaBischoff requested changes
TC04:
Nachbedingung | es ist nicht möglich das selbe Experiment mehrmals auszuwählen
--> Warum? Ich würde noch ergänzen, das das Experiment nur mit Klick auf das Warenkorb Symbol gewählt werden kann. Wenn man nochmal draufklickt, geht es wieder raus. 

TC25 - NFAU-2 - Eingaben geschehen nicht in Pop-Ups (manueller Test)
Wäre es hier nicht wichtig zu erwähnen, das man mit mehreren Browsern testen sollte? Kann ja sein, das das in einem vielleicht als Popup angezeigt wird.. :o

Ansonten finde ich es sehr gut :)

2021-02-05 08:48 UTC, AlenaBischoff commented
@Greyhound993 Da du der Ansprechpartner bist, schau mal ob du mir zustimmst :)

2021-02-06 02:22 UTC, Greyhound993 commented
> TC04:
> Nachbedingung | es ist nicht möglich das selbe Experiment mehrmals auszuwählen
> --> Warum? Ich würde noch ergänzen, das das Experiment nur mit Klick auf das Warenkorb Symbol gewählt werden kann. Wenn man nochmal draufklickt, geht es wieder raus.
> 
> TC25 - NFAU-2 - Eingaben geschehen nicht in Pop-Ups (manueller Test)
> Wäre es hier nicht wichtig zu erwähnen, das man mit mehreren Browsern testen sollte? Kann ja sein, das das in einem vielleicht als Popup angezeigt wird.. :o
> 
> Ansonten finde ich es sehr gut :)

Zu TC04 da hast du komplett recht, nur durch die TC Formulierungen kommt das ein bisschen komisch rüber. Das was du beschreibst ist das was der Tester händisch tut und im TC ist das ganze nur mit Bedingungen beschrieben. Deswegen würde ich es so lassen wie es ist, weil wir sonst alle andren TC umschreiben müssten. 

Zu TC25 müssen wir die Browser nicht extra erwähnen weil, wir in einem andren Dokument (glaub das war swr) erwähnt haben das wir auf Edge, Chrome ... das Ding lauffähig haben müssen. Somit muss jeder Test mal in jedem gennannten Browser mal durchlaufen. 

Ich würde zu beiden keine Änderung bevorzugen. 

Alles geklärt oder noch Diskussionsbedarf? :)

2021-02-06 11:30 UTC, Schmiddl99 commented
> 
> 
> > TC04:
> > Nachbedingung | es ist nicht möglich das selbe Experiment mehrmals auszuwählen
> > --> Warum? Ich würde noch ergänzen, das das Experiment nur mit Klick auf das Warenkorb Symbol gewählt werden kann. Wenn man nochmal draufklickt, geht es wieder raus.
> > TC25 - NFAU-2 - Eingaben geschehen nicht in Pop-Ups (manueller Test)
> > Wäre es hier nicht wichtig zu erwähnen, das man mit mehreren Browsern testen sollte? Kann ja sein, das das in einem vielleicht als Popup angezeigt wird.. :o
> > Ansonten finde ich es sehr gut :)
> 
> Zu TC04 da hast du komplett recht, nur durch die TC Formulierungen kommt das ein bisschen komisch rüber. Das was du beschreibst ist das was der Tester händisch tut und im TC ist das ganze nur mit Bedingungen beschrieben. Deswegen würde ich es so lassen wie es ist, weil wir sonst alle andren TC umschreiben müssten.
> 
> Zu TC25 müssen wir die Browser nicht extra erwähnen weil, wir in einem andren Dokument (glaub das war swr) erwähnt haben das wir auf Edge, Chrome ... das Ding lauffähig haben müssen. Somit muss jeder Test mal in jedem gennannten Browser mal durchlaufen.
> 
> Ich würde zu beiden keine Änderung bevorzugen.
> 
> Alles geklärt oder noch Diskussionsbedarf? :)

Also können wir das Ticket abschließen und mergen, oder?

2021-02-06 13:47 UTC, merged