159_gregor_julius_correction_of_project-plan
Schmiddl99/experimenteverwaltung-i2 pull request #188
Opened 2021-02-04 15:19 UTC by Greyhound993

RF verbessert, Überall Email-Adressen verwendet, tags korrigiert

refs #159

2021-02-06 13:34 UTC, Schmiddl99 reviewed
wie gesagt, schau nochmal über die Zeile 71, ob das verständlich genug ist?

2021-02-07 15:53 UTC, Schmiddl99 requested changes
Nur einen RF und dann musst du dich Entscheiden, ob I02 oder I2 um die Iterationen zu nummerieren.

2021-02-07 15:53 UTC, Schmiddl99 commented on Dokumentationen/project_management/project_plan.adoc
> +Da während unsres Projekts die Corona-AHA Regeln gegolten haben, wurden auf physische Treffen komplett verzichtet. Die komplette Kommunikation lief über die Programme *Whatsapp* , *Discord* und *MS-T
```suggestion
Da während unseres Projekts die Corona-AHA Regeln gegolten haben, wurden auf physische Treffen komplett verzichtet. Die komplette Kommunikation lief über die Programme *Whatsapp* , *Discord* und *MS-Teams*.
```

2021-02-07 15:53 UTC, Schmiddl99 commented on Dokumentationen/project_management/project_plan.adoc
> +* *Shared Vision*: Diese OpenUP-Praktik verbessert die Akzeptanz des späteren Produktes durch alle Stakeholder. In unserem Fall strebten wir die Übereinstimmung über die <<Vision: {project-name}, Vis
```suggestion
* *Shared Vision*: Diese OpenUP-Praktik verbessert die Akzeptanz des späteren Produktes durch alle Stakeholder. In unserem Fall strebten wir die Übereinstimmung über die <<Vision: {project-name}, Vision>> und die damit beschriebene Opportunity gemeinsam mit dem Themensteller an. Das Team konnte diese Übereinstimmung in <<Iteration Plan 03: {project-name}, Iteration I03>> erreichen.
```
Bleibe bitte bei der Nummerierung von I**0**3, weil sonst müssen wir alles nochmal ändern 😅

2021-02-07 22:33 UTC, TobiasK20 commented
- step 1: merge branch 160 auf *diesen 159* (siehe PR 195) (Tobias verantwortlich) 
- step 2: *VOR merge* des 159 auf main bitte Nachricht an @richardboehme für Kontrolle ob alles richtig lief!!

2021-02-08 14:34 UTC, merged