Erste Korrektur
Schmiddl99/experimenteverwaltung-i2 pull request #198
Opened 2021-04-20 14:26 UTC by s80523

Hab erstmal alles, was eindeutig ohne großen Inhalt ist behoben.
Den Rest müssen wir zusammen machen - evtl. in einem Extrameeting. Ich sollte gesammelt haben, was noch gemacht werden muss. 

refs #197

2021-04-21 15:50 UTC, richardboehme requested changes
Das sieht gut aus, danke! Habe noch paar Anmerkungen und Fragen ergänzt :)

2021-04-21 15:50 UTC, richardboehme commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* Erarbeitung des Use Case Model
Müsste man das so schreiben: `Erarbeitung des Use Case Models` oder macht man das wegen dem englischem Wort nicht?

2021-04-21 15:50 UTC, richardboehme commented on Dokumentationen/project_management/project_plan.adoc
> +| * Erarbeitung des Domänenmodell
Selbes wie oben: `Erarbeitung des Domänenmodells` oder?

2021-04-21 15:50 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +* Warenkorb-Funktio: Die Experimente können nach Festlegung der Voreinstellungen für eine Vorlesung in einen Warenkorb abgelegt werden. Anschließend kann die Reihenfolge noch angepasst werden. Nach e
```suggestion
* Warenkorb-Funktion: Die Experimente können nach Festlegung der Voreinstellungen für eine Vorlesung in einen Warenkorb abgelegt werden. Anschließend kann die Reihenfolge noch angepasst werden. Nach erfolgreicher Buchung werden sie dem persönlichen Journal hinzugefügt.
```

2021-04-21 15:50 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +//Einige Ideen des Teams wurden vom Themensteller abgelehnt. Da das Team I2 dennoch von der Notwendigkeit und dem Nutzen dieser skizzierten Funktionen für die Vorlesungsassistenz überzeugt ist, wolle
Warum das raus? Da war doch kein Kommentar dran oder?

2021-04-22 09:46 UTC, s80523 commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* Erarbeitung des Use Case Model
War ich mir auch nicht sicher, hab dann intuitiv entschieden und weiß ehrlich gesagt nicht, wie wir das jetzt überprüfen können. Wir können aus "Model" ein deutsches "Modell" machen und dann passt "Erarbeitung des Use Case Modells". :D

2021-04-22 10:02 UTC, s80523 commented on Dokumentationen/requirements/vision.adoc
> +//Einige Ideen des Teams wurden vom Themensteller abgelehnt. Da das Team I2 dennoch von der Notwendigkeit und dem Nutzen dieser skizzierten Funktionen für die Vorlesungsassistenz überzeugt ist, wolle
Er hatte es komplett markiert und deswegen bin ich davon ausgegangen, dass das rauskommentiert werden soll.

2021-04-22 10:03 UTC, s80523 commented on Dokumentationen/project_management/project_plan.adoc
> +| * Erarbeitung des Domänenmodell
Absolut richtig, hier hab ichs einfach verpeilt. :D

2021-04-22 15:45 UTC, richardboehme commented on Dokumentationen/project_management/iteration_plan_02.adoc
> +* Erarbeitung des Use Case Model
Würde es nicht ändern, da überall anders auch Use Case Model steht und wir das nicht hier eindeutschen sollten dafür. Wir lassen es einfach so :D

2021-04-22 15:46 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +//Einige Ideen des Teams wurden vom Themensteller abgelehnt. Da das Team I2 dennoch von der Notwendigkeit und dem Nutzen dieser skizzierten Funktionen für die Vorlesungsassistenz überzeugt ist, wolle
Die Markierung war glaube ich von uns so gewollt. Das machen diese #-Symbole um den Text herum :D

2021-04-23 13:15 UTC, s80523 commented on Dokumentationen/requirements/vision.adoc
> +//Einige Ideen des Teams wurden vom Themensteller abgelehnt. Da das Team I2 dennoch von der Notwendigkeit und dem Nutzen dieser skizzierten Funktionen für die Vorlesungsassistenz überzeugt ist, wolle
Wow, das ist jetzt natürlich peinlich. Zu meiner Verteidigung: es war exakt die selbe Farbe! :D
Aber gut zu wissen, dann kommts wieder rein. :)

2021-04-24 13:32 UTC, Greyhound993 approved these changes
Super Arbeit! Danke William!!, bitte noch den Rest ausbessern. Hab auch zwei Kommentare hinterlassen. Würde das hier dann erst mal mergen das wir dann die nächsten Kommentare angehen können :)

2021-04-24 13:32 UTC, Greyhound993 commented on Dokumentationen/requirements/use_case_01.inc.adoc
>  ==== Abbruch des Buchungsvorgangs
Bei US 01 bitte noch Exp. ausschreiben, Exp. -> Experimente

2021-04-24 13:32 UTC, Greyhound993 commented on Dokumentationen/requirements/use_case_07.inc.adoc
> +//--- keine besonderen Anforderungen ---
Bei UC 8 bitte auch noch Alternative Abläufe etc.( siehe andre UCs) löschen

2021-04-26 13:56 UTC, merged