Beleg Korrektur Part 2
Schmiddl99/experimenteverwaltung-i2 pull request #225
Opened 2021-05-15 14:53 UTC by Greyhound993

Sehr viele Änderungen, zuviel zum aufzählen

refs. #221

2021-05-19 22:10 UTC, s80523 requested changes

2021-05-19 22:10 UTC, s80523 commented on Dokumentationen/requirements/use_case_01.inc.adoc
> +Versucht der Nutzer mit null Experimenten oder einen Kommentar, der länger als x Zeichen ist zu speichern erscheint eine Fehlermeldung, die den Nutzer auf seinen Fehler hinweißt.
```suggestion
Versucht der Nutzer eine Buchung mit null Experimenten oder einem Kommentar, der länger als x Zeichen ist zu speichern, erscheint eine Fehlermeldung, die den Nutzer auf seinen Fehler hinweist. 
```

2021-05-19 22:10 UTC, s80523 commented on Dokumentationen/requirements/use_case_03.inc.adoc
> +Wenn in der ausgewählte Woche des Dozenten keine Buchungen existierten wird eine Meldung ausgegeben, die beinhaltet, dass keine Buchnungen vorhanden sind.
```suggestion
Wenn in der ausgewählten Woche des Dozenten keine Buchungen existieren, wird eine Meldung ausgegeben, die beinhaltet, dass keine Buchungen vorhanden sind. 
```

2021-05-19 22:10 UTC, s80523 commented on Dokumentationen/requirements/use_case_08.inc.adoc
> +Versucht der Nutzer mit null Experimenten oder einen Kommentar, der länger als x Zeichen ist zu speichern erscheint eine Fehlermeldung, die den Nutzer auf seinen Fehler hinweißt.
```suggestion
Versucht der Nutzer eine Buchung mit null Experimenten oder einem Kommentar, der länger als x Zeichen ist zu speichern, erscheint eine Fehlermeldung, die den Nutzer auf seinen Fehler hinweist. 
```

2021-05-19 22:10 UTC, s80523 commented on Dokumentationen/project_management/project_plan.adoc
> +* Es besteht ein großer Unterschied zwischen dem Verständis die Agile Softwareentwicklung theoretisch zu verstehen oder in der Praxis anzuwenden.
```suggestion
* Es gibt Differenzen zwischen dem theoretischen Verständnis bezüglich der agilen Softwareentwicklung und ihrer Umsetzung. 
```

2021-05-19 22:10 UTC, s80523 commented on Dokumentationen/project_management/project_plan.adoc
> +* Der Kunde muss für sein System selbst die Verantwortung tragen und nicht das Entwickler-Team. Es reicht aus den Kunden auf fragwürdige Anforderungen hinzuweisen, sie werden aber auf Wunsch umgesetz
```suggestion
* Der Kunde muss für sein System selbst die Verantwortung tragen und nicht das Entwickler-Team. Es reicht aus, den Kunden auf fragwürdige Anforderungen hinzuweisen, sie werden aber auf Wunsch umgesetzt, solange sie ethisch vertretbar sind.
```

2021-05-30 12:32 UTC, richardboehme commented
bump @Greyhound993

2021-05-31 11:21 UTC, Greyhound993 commented on Dokumentationen/requirements/use-case_model.adoc
> +|<< Use-Case: Dozentenwoche ansehen,Dozentenwoche ansehen >>
Das ist eine Verlinkung, des sollte so passen

2021-05-31 14:13 UTC, merged