Projekt Bericht
Schmiddl99/experimenteverwaltung-i2 pull request #245
Opened 2021-06-07 11:32 UTC by Greyhound993

2021-06-23 22:02 UTC, s80523 requested changes
Soweit zur Planung und zur Einleitung, den Durchführungspart gehe ich noch durch. Vergiss nicht die ganzen Links noch einzufügen, das muss (wenn ich mich richtig entsinne) auch noch bei anderen Dokumenten gemacht werden. 
Allgemeines Feedback: Soweit sogut. Ich denke du hast das Wichtigste gesagt und gut strukturiert ist bis hier hin auch alles, würde ich behaupten. Um ehrlich zu sein fällt es mir manchmal schwer zu erkennen, was du inhaltlich ausdrücken willst, aber ich denke, dass das schon klar gehen wird. :)
Du solltest nur evtl. kein Schriftsteller werden, Gregor. 😉

2021-06-27 14:17 UTC, s80523 requested changes
Gute Arbeit Gregor. Viele Details und Gedanken, die mir als sehr wichtig und prägnant erscheinen. Folgende Fragen stelle sich noch: 
- Du meintest selbst, dass wir beschreiben sollen, was und die Paarprogrammierung gebracht hat - kommt das mit ins Ergebnis oder soll das hier mit rein?
- die Login-Problematik ist nirgends konkret erklärt, nur nebenbei und ihr Ausgang, oder täusche ich mich? Evtl. nochmal genauer ausdrücken.
- vergiss nicht alle LINKS noch einzufügen
- teilweise habe ich das Gefühl, dass genauere Beschreibungen oder Entscheidungserklärungen fehlen. Bsp.: Kundenmeeting in Zeile 30 - was ist das passiert. 

Im Groben und Ganzen sollte es aber soweit passen, denke ich. Am Ausdruck mangelt es doch des Öfteren mal, aber der Inhalt ist schön rund und einheitlich, weswegen hier alles im grünen Bereich ist, wie ich denke. Gute Arbeit!

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Am Anfang wurde das System vom Projektmanager vorgestellt. Anwesend waren hier Frau Dr. Krawietz, Herr Heisig und Herr Zirkelbach (Coach). Die Vorstellung verlief sehr gut bis auf einen Fehler, dass
```suggestion
Am Anfang wurde das System vom Projektmanager vorgestellt. Anwesend waren hier Frau Dr. Krawietz, Herr Heisig und Herr Zirkelbach (Coach). Die Vorstellung verlief sehr gut, bis auf einen Fehler, dass sich die Buttons der Menüleiste übereinandergeschoben haben und somit die Menüinhalte verdeckt wurden, bei nicht ausreichender Bildschirmbreite.
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Anschließend wurde vom Projektmanger der Vorschlag unterbreitet, dass wenn man auf die Umsetzung von UC10 verzichten würde das Team mehr Zeit für andere Anforderungen hätte. Die Lösung wäre hier, das
```suggestion
Anschließend wurde vom Projektmanger der Vorschlag unterbreitet, dass durch den Verzicht auf die Umsetzung von UC10 mehr Zeit für andere Anforderungen entstehen würde. Die Lösung wäre hier, dass die Studiengänge hart ins System gecodet werden und wenn es Änderungen bei den Studiengängen geben sollte, die nach Meinung des Teams selten seien, diese auch wieder im System geändert werden. Eine ensprechende Beschreibung und Anleitung sollte in der Betriebsdokumentation beigelegt werden.
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Ein weiterer Vorschlag war auch auf die Filterfunktion bei dem Journal zu verzichten, um auch hier mehr Zeit zu gewinnen. (Die Vorschläg waren im Vorfeld mit dem Team abgesprochen worden). Der Kunde
```suggestion
Ein weiterer Vorschlag war auch, auf die Filterfunktion im Journal zu verzichten, um auch hier mehr Zeit zu gewinnen. (Die Vorschläg waren im Vorfeld mit dem Team abgesprochen worden). Der Kunde stimmte bei beiden zu, bestand aber darauf, dass die Filterfunktion in die Zukunftsaussicht mitaufgenommen werden würde. Der Projekmanager bestätigte dies.  
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Es soll eine Notification geben die den Admin darauf hinweißt, dass an einem bereits ausgedruckten Wochenplan noch eine Änderung durch einen Dozenten geschen ist
```suggestion
** Es soll eine Notification geben die den Admin darauf hinweist, dass an einem bereits ausgedruckten Wochenplan noch eine Änderung durch einen Dozenten geschehen ist
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Es soll möglich sein die Voreinstellung auch noch im nachhinein zu verändern.
```suggestion
** Es soll möglich sein, die Voreinstellung auch noch im Nachhinein zu verändern. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die gewünschten Änderungen wurde alle akzeptiert, nur die Änderungen bezüglich der Notification löste beim Projektmanager Unverständnis aus, da genau dieser Vorschlag dem Kunden bei TSM2 gemacht wurd
```suggestion
Die gewünschten Änderungen wurde alle akzeptiert, nur die Änderungen bezüglich der Notification löste beim Projektmanager Unverständnis aus, da genau dieser Vorschlag dem Kunden bei TSM2 gemacht wurde und auf Ablehnung traf.
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Aus Zeitgründen wurden die Anwender- und Admintests nicht im Meeting durchgeführt sondern, Frau Dr. Krawietz und Herr Heisig wurden gebeten diese Zuhause zu erledigen. Beide akzeptierten den Vorschla
```suggestion
Aus Zeitgründen wurden die Anwender- und Admintests nicht im Meeting durchgeführt. Frau Dr. Krawietz und Herr Heisig wurden gebeten, diese Zuhause zu erledigen. Beide akzeptierten den Vorschlag und fanden die Idee mit den Usertests gut. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Auf Wunsch des Kunden wurde nach dem TSM5, dem Kunden und Frau Dr. Krawietz Zugang zu dem Testsystem gewährt. Einmal natürlich um die Usertests durchführen zu können, aber auch um das System besser k
```suggestion
Auf Wunsch des Kunden wurde nach dem TSM5, dem Kunden und Frau Dr. Krawietz Zugang zu dem Testsystem gewährt. Einmal natürlich um die Usertests durchführen zu können, aber auch um das System besser kennenlernen zu können. Wir hielten dies für eine gute Idee, da wir glaubten, es sei besser selbst mit dem System arbeiten zu können, als nur auf eine Präsentation angewiesen zu sein. Der Zugang wurde gewährt. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Retrospective
```suggestion
* Retrospektive
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Das sehr positive Feedback des erste Inkrement mit dem Kunden freut uns sehr. Da wir im laufe des Projekt ja immer wieder Verständigungsschwierigkeiten hatten, war bei uns im das Risko präsent, da
```suggestion
** Das sehr positive Feedback des erste Inkrement mit dem Kunden freut uns sehr. Da wir im Laufe des Projektes ja immer wieder Verständigungsschwierigkeiten hatten, war bei uns immer das Risko präsent, dass der Kunde nicht zufrieden wäre, mit unser Arbeit. Dass dieser Fall nun nicht eingetreten war, erleichterte uns sehr. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Inkremente sind unglaublich wichtig, für den Kunden sowie für die Entwickler. Kein Wireframe oder Protokoll kann mit der Informationsdichte oder dem Verständnisaustausches einer wirklichen Vorführ
```suggestion
** Inkremente sind unglaublich wichtig, für den Kunden sowie für die Entwickler. Kein Wireframe oder Protokoll kann mit der Informationsdichte oder dem Verständnisaustausch einer wirklichen Vorführung mithalten. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Experimentefeld Geräte optimieren
```suggestion
* Experimentefeld "Geräte" optimieren 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Der Drucken Button bei der Wochenplanansicht und der Experiment Hinzufügen Button bei dem Journal wurden erfolgreich implementiert.
```suggestion
Der "Drucken" Button bei der Wochenplanansicht und der "Experiment Hinzufügen" Button bei dem Journal wurden erfolgreich implementiert. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Da wir die Forderung nach einem Buchungssystem als abgeschlossen betrachteten, kamen wir der Aufgabe nach das Experimentenfeld Geräte zu optimieren. Das Ziel war es die Ausgabe der Geräte in der über
```suggestion
Da wir die Forderung nach einem Buchungssystem als abgeschlossen betrachteten, kamen wir der Aufgabe nach das Experimentenfeld "Geräte" zu optimieren. Das Ziel war es, die Ausgabe der Geräte in der Übersichtsliste zu verbessern, da der Kunde viel Zeit damit verschwendet, die Geräte zu finden. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Wir analysierten das Problem und kamen zu dem Schluss, dass hier eine Stringsuche am besten geeignet war. Hier war der Vorteil, dass die Geräte beliebig erweitert werden konnten ohne die Suche anpass
```suggestion
Wir analysierten das Problem und kamen zu dem Schluss, dass hier eine Stringsuche am besten geeignet war. Hier war der Vorteil, dass die Geräte beliebig erweitert werden konnten, ohne die Suche anpassen zu müssen. 
```

2021-06-27 14:17 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die Vorführung der Buttons und des optimierten Gerätefelds wurden von dem Kunden erfreut angenommen. Allerdings wurden von Ihm noch einige Änderungen gewünscht. Die meisten davon waren visuller Natur
```suggestion
Die Vorführung der Buttons und des optimierten Gerätefelds wurden von dem Kunden erfreut angenommen. Allerdings wurden von Ihm noch einige Änderungen gewünscht. Die meisten davon waren visuller Natur, wie die Umbennung und Umfärbung von Buttons. Eine jedoch war direkt so groß, dass der Projektmanager sie direkt im Meeting als Outscope deklarieren konnte. Der Kunde forderte noch die Einführung einer zusätzlichen Rolle, die des Assistenten. Eine genaue Auflistung der Forderungen findet man in der Vision. LINK!!!
```

2021-06-28 06:35 UTC, s80523 requested changes
Ergebnis sollte jetzt auch soweit i.O. sein!

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Diese Ziel wurde erreicht, es ist nun mit unsrem System möglich eine Komplette Vorlesung, mit dem Studiengang, einem optionalen Titel, dem Datum, der Uhrzeit und den entsprechenden Experimenten, die
```suggestion
Diese Ziel wurde erreicht, es ist nun mit unserem System möglich eine komplette Vorlesung, mit dem Studiengang, einem optionalen Titel, dem Datum, der Uhrzeit und den entsprechenden Experimenten, die in der Vorlesung vorgeführt werden sollen, zu planen und zu buchen. Dies wurde erreicht mit Hilfe der *Voreinstellung*, welche die Kerndaten der Vorlesung, wie Studiengang, optionaler Titel, Datum und Uhrzeit festlegen. Die Auswahl der Experimente erfolgt über ein Overlay in der Experimentenübersicht, in dem man durch Klicken auf ein Einkaufswagensymbol Experimente zu Vorlesung hinzufügen oder abwählen kann. Beim Buchungsabschluss wird dem Nutzer eine Übersicht der ausgewählten Experimente im *Warenkorb* angezeigt, wo er nun auch die Reihenfolge der Experimente verändern kann. Zusätzlich kann er bei Bedarf auch einen Kommentar pro Vorlesung hinterlassen. 
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Auch dieses Ziel wurde erreicht und wird von uns durch das *Journal* umgesetzt. Hier kann sich der Dozent alle bisher gebuchten Vorlesungen ansehen und diese, wenn die Vorlesung noch nicht gehalten w
```suggestion
Auch dieses Ziel wurde erreicht und wird von uns durch das *Journal* umgesetzt. Hier kann sich der Dozent alle bisher gebuchten Vorlesungen ansehen und diese, wenn die Vorlesung noch nicht gehalten wurde, verändern. Hier können Experimente hinzugefügt werden oder aus der Buchung gelöscht werden. Auch lässt sich hier auch die Reihenfolge der Experimente und der Kommentar bearbeiten. Die gesammte Buchung kann hier auch gelöscht werden, wenn sie noch in der Zukunft liegt. 
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Ein weiteres Ziel, dass wir durch die *Dozentenwoche* erreichen konnten. Durch klicken auf die Dozentenwoche, kann der Dozent nach Auswahl des Jahrs und der Kalenderwoche sich eine Wochenplanübersich
```suggestion
Ein weiteres Ziel, dass wir durch die *Dozentenwoche* erreichen konnten, bestand in einer strukturierten Darstellung der Buchungen. Durch klicken auf die Dozentenwoche, kann der Dozent sich nach Auswahl des Jahrs und der Kalenderwoche eine Wochenplanübersicht erstellen lassen. Diese wird dann online angezeigt und kann über die Druckfunktion des Browsers gedruckt oder als PDF generiert werden. 
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Der Admin verfügt über die selbe Möglichkeit, kann aber zusätzlich noch den Dozenten auswählen, dessen Dozentenwoche er einsehen möchte.
```suggestion
Der Admin verfügt über die gleiche Möglichkeit, kann aber zusätzlich noch den Dozenten auswählen, dessen Dozentenwoche er einsehen möchte. 
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Ziel erreicht durch den *Login*. Durch unterschiedliche Userrollen ist es möglich, die Nutzer mit Ihren unterschiedlichen Funktionen und Rechten voneinander zu trennen. Auch wird es so ermöglicht, da
```suggestion
Ziel erreicht durch den *Login*. Durch unterschiedliche Userrollen ist es möglich, die Nutzer mit ihren unterschiedlichen Funktionen und Rechten voneinander zu trennen. Auch wird es so ermöglicht, dass der Admin keine Vorlesungen der Dozenten bearbeiten kann, oder die Dozenten Vorlesungen anderer Dozenten verändern können. Weiterhin hat der Admin auf alle Funktionen Zugriff, die der Experimentenbearbeitung oder allgemeinen Systemverwaltung (Nutzerverwaltung etc.) ensprechen. 
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Durch hinzufügen einer Sucheleiste in der Eingabe Maske, kann der Admin sich nun gezielt Geräte anzeigen lassen. Das Ziel wurde erreicht.
```suggestion
Durch Hinzufügen einer Suchleiste in der Eingabemaske, kann der Admin sich nun gezielt Geräte anzeigen lassen. Das Ziel wurde erreicht.
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> += Begründung für das nicht Erfüllen aller Ziele
```suggestion
= Begründung für das Nichterfüllen von Zielen
```

2021-06-28 06:35 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Wir hatten nicht genug Zeit alle Ziele zu erfüllen. Dadurch das zwei Teammitglieder uns am Anfang des Semesters verlassen haben und uns nur ein neues Teammitglied hinzugefügt wurde, fehlte uns die ko
```suggestion
Wir hatten nicht genug Zeit alle Ziele zu erfüllen. Dadurch, dass zwei Teammitglieder uns am Anfang des Semesters verlassen haben und uns nur ein neues Teammitglied hinzugefügt wurde, fehlte uns die komplette Arbeitskraft eines Teammitglied über das Semester. Auch die Einarbeitungszeit des neuen Mitglieds konnte nicht produktiv für das Projekt genutzt werden. Auch die vielen Änderungen des Kunden, behinderten uns stark am eigentlichen Arbeiten an der Aufgabe, da eigentlich beschlossene Aufgaben immer wieder neu analysiert und dokumentiert werden mussten. Auch die Korrektur des Belegs am Anfang des Semesters kostete viel Arbeitszeit, die aber für das System keine Fortschritte gebracht hat. 
```

2021-06-28 08:50 UTC, s80523 requested changes

2021-06-28 08:50 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Bei dem Projekt in SE gab es für mich einige Höhen und einige Tiefen. Ich durfte durch das Projekt, einige tolle Bekanntschaften machen und auch die Lehrkörper aus einer anderen Perspektive kannenler
```suggestion
Bei dem Projekt in SE gab es für mich einige Höhen und einige Tiefen. Ich durfte durch das Projekt, einige tolle Bekanntschaften machen und auch die Lehrkörper aus einer anderen Perspektive kennenlernen. Zum Beispiel wurde mir erst hier Bewusst, dass es auch an unsere Hochschule einige Menschen gibt, die sich gegen Veränderung sträuben und es ein harter Kampf sein kann, neue Systeme in den Arbeitsalltag zu integrieren. Diese Erfahrung machte ich so zum ersten Mal und dachte bis jetzt immer, diese typischen Aussagen wie „aber früher war alles besser“, würden sich auf mein Berufsleben begrenzen. 
```

2021-06-28 08:50 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Und ich bin auch dankbar dafür immer wieder augmentiert haben zu müssen warum und wieso und weshalb und weswegen wir unsere Entscheidungen getroffen haben. Dies lenkte meinen Fokus auf die Wirklichen
```suggestion
Und ich bin auch dankbar dafür, immer wieder argumentiert haben zu müssen, warum und wieso und weshalb und weswegen wir unsere Entscheidungen getroffen haben. Dies lenkte meinen Fokus auf die wirklichen Hintergründe einer Forderung des Kunden. Es war zwar öfter mehr als frustrierend, das gebe ich zu, aber im Nachhinein betrachtet glaube ich, dass ich so auch auf vielleicht noch schwierigere oder komplizierte Kunden vorbereitet wurde. 
```

2021-06-28 08:50 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Die ewige Anfertigung von Dokumentationsbelegen empfand ich teilweise mehr als hinderlich als förderlich. Ich dachte oft, es ist doch klar warum wir dies oder das machten, oder das der Detailgrad ein
```suggestion
Die ewige Anfertigung von Dokumentationsbelegen empfand ich teilweise mehr als hinderlich, als förderlich. Ich dachte oft, es ist doch klar, warum wir dies oder das machten, oder das der Detailgrad einfach zu groß war, der in den Belegen gefordert wurde. Aber als dann der Punkt im Projekt kam, an dem wir die alten TCs bearbeiten wollten und wir uns kaum erklären konnten, was hier eigentlich was macht und warum überhaupt, überdachte ich meine Einstellung. Man kann einfach nie sagen, wie es nach einem Projektabschluss weiter geht und was ein zukünftiger Entwickler vielleicht noch alles für Zusatzinformationen benötigt. Heute sage ich, dass die Dokumentation mehr als wichtig ist und auch stets, auch im Privatbereich eingehalten werden sollte. 
```

2021-06-28 15:38 UTC, Greyhound993 commented on Dokumentationen/Projekt Bericht/Planung.adoc
> +Die Aufgaben wurden hauptsächlich nach Interessen- und Expertisengebieten verteilt. Das Team einigte sich darauf, das der Rollenverantwortliche sich hauptsächlich um die Dokumentationspflichten und A
Ich lass Weeklys drin, hatten wir im ersten Beleg auch so :) Okay ?

2021-06-29 19:23 UTC, s80523 approved these changes

2021-06-30 12:37 UTC, richardboehme requested changes
Erstmal: Der Projektbericht ist wirklich gut geschrieben, danke dafür! 😄 Ich habe hier noch ein paar kleine Anmerkungen gemacht. Das meiste bezieht sich aber auf Rechtschreibfehler oder Ausdrucksanpassungen.

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Durch die Änderungen des Kunden im TSM4 musste auch das Architecture-Notebook entsprechend angepasst werden. Die Änderungen wurden unter Aufsicht des Analysten vorgenommen, da er denn besten Überblic
```suggestion
Durch die Änderungen des Kunden im TSM4 musste auch das Architecture-Notebook entsprechend angepasst werden. Die Änderungen wurden unter Aufsicht des Analysten vorgenommen, da er den besten Überblick über die neuen Anforderungen hatte. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Der UC01 wurde erfolgreich implemntiert. Um bei der Implementierungen einen perfekten Fachaustausch zu gewährtleiten, verwenden wir hier und bei jeder weiteren Implementierung die Pairprogrammierung.
```suggestion
Der UC01 wurde erfolgreich implementiert. Um bei der Implementierungen einen perfekten Fachaustausch zu gewährleisten, verwenden wir hier und bei jeder weiteren Implementierung die Pairprogrammierung. An der Pairprogrammierung waren der Developer und der Analyst beteiligt. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Wir kamen zu dem Entschluss, dass es eine Verbesserung des Organisationsaufwands wäre, wenn wir die Verbesserungen des Belegs nun nicht mehr durchgehend planen würden, sondern dazu übergehen, sie mit
```suggestion
Wir kamen zu dem Entschluss, dass es eine Verbesserung des Organisationsaufwands wäre, wenn wir die Verbesserungen des Belegs nun nicht mehr durchgehend planen würden, sondern dazu übergehen, sie mit normalen Arbeiten am Beleg zu verbinden. Dies wurde auch in der Work-Item-List mit einem durchgehenden Issue realisiert und es wurde ein Dokument in Microsoft Teams erstellt mit den noch zu erledigten Verbesserungen, sodass nichts vergessen wird.  
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +|Corona bedingte Zeitmanagementprobleme | Gelöst | Da das Corona Hygienekonzept zur erneuten Schließung von Kindergärten geführt hat, kann {PG}, der Vater von zwei Kindern ist, sich nicht in dem Umfa
```suggestion
|Corona bedingte Zeitmanagementprobleme | Gelöst | Da das Corona Hygienekonzept zur erneuten Schließung von Kindergärten geführt hat, kann {PG}, der Vater von zwei Kindern ist, sich nicht in dem Umfang dem Projekt widmen, wie er es möchte. Dies führt zu dem Problem, dass er bei seinem Workload unterstützt werden muss, was ein großes Zeitproblem mit sich bringt. (Coach wurde über dieses "außergewöhnliche" Problem informiert). Das Problem wurde in der Risklist vermerkt und als Lösung wurde beschlossen, dass wenn Zeitprobleme jeder Art auftauchen sollten, diese so schnell wie möglich der Gruppe mitzuteilen sind, sodass schneller gehandelt werden kann. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Das Gruppen- und Arbeitsklima ist im grünen Bereich. Siehe <<Iteration 06, Iterations-Umfrage>>
Der Link hier führt ins leere oder?

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Reperatur oder Entfernung alter TCs
```suggestion
* Reparatur oder Entfernung alter TCs
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Ein weiterer Teil unsere Notfallmanagements war Vincent Thelang zu kontaktiern, ob er uns vielleicht weiterhelfen könne. Obwohl wir seine Hilfe bezüglich der alten TCs zum Meetingzeitpunkt (01.06.202
```suggestion
Ein weiterer Teil unsere Notfallmanagements war Vincent Thelang zu kontaktieren, ob er uns vielleicht weiterhelfen könne. Obwohl wir seine Hilfe bezüglich der alten TCs zum Meetingzeitpunkt (01.06.2021) glücklicherweise nicht mehr benötigten, hielten wir dennoch einen Fachaustausch ab. Hier ergaben sich zwar keine neuen Ergebnisse, aber Herr Thelang meinte, dass wir auf einem guten Weg wären. An dem Fachaustausch beteiligten sich der Projektmanager und der Developer, da hier die Bezugsgrößen von Projektorganisation und Projektumsetzung am größten waren. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Bei der Betrachung der Use-Cases UC05, UC06 und UC07 bemerkten wir, dass wir bei Ihrer Erstellung zu granular vorgegenagen waren. Da sich alle Use-Cases auf die Dozentenwoche bezogen, überführten wir
```suggestion
Bei der Betrachtung der Use-Cases UC05, UC06 und UC07 bemerkten wir, dass wir bei Ihrer Erstellung zu granular vorgegangen waren. Da sich alle Use-Cases auf die Dozentenwoche bezogen, überführten wir diese in UC03. Somit war ein leichteres Verständnis und größere Übersichtlichkeit gegeben. Hier beteiligte sich der Analyst tatkräftig, sodass keine Anforderungen verloren gingen. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Der UC03 wurde im C4 Modell erfolgreich umgestzt.
```suggestion
Der UC03 wurde im C4 Modell erfolgreich umgesetzt.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> + Die TCs für UC01 wurden erfolgreich implementiert. Das Resultat war erfolgreich.
```suggestion
Die TCs für UC01 wurden erfolgreich implementiert. Das Resultat war erfolgreich.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Der UC03 wurde Implementiert. Hier haben Developer und Analyst Pairprogrammierung betrieben.
```suggestion
Der UC03 wurde implementiert. Hier haben Developer und Analyst Pairprogrammierung betrieben. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Das Feedback des Coaches und des Fachaustausch wurden sehr postiv vom Team aufgenommen. Wir fühlen in unserem Tun mehr bestärkt und stehen sicherer hinter unseren Entscheidungen.
```suggestion
** Das Feedback des Coaches und des Fachaustausch wurden sehr positiv vom Team aufgenommen. Wir fühlen uns in unserem Tun mehr bestärkt und stehen sicherer hinter unseren Entscheidungen.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Implementierung von TC03
Sicher, dass hier TC03 (Leerer Warenkorb darf nicht zur Buchung führen) gemeint ist?

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Es soll eine Notification geben die den Admin darauf hinweist, dass an einem bereits ausgedruckten Wochenplan noch eine Änderung durch einen Dozenten geschehen ist
```suggestion
** Es soll eine Benachrichtigung geben, die den Admin darauf hinweist, dass an einem bereits ausgedruckten Wochenplan noch eine Änderung durch einen Dozenten geschehen ist.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die gewünschten Änderungen wurde alle akzeptiert, nur die Änderungen bezüglich der Notification löste beim Projektmanager Unverständnis aus, da genau dieser Vorschlag dem Kunden bei TSM2 gemacht wurd
```suggestion
Die gewünschten Änderungen wurde alle akzeptiert, nur die Änderungen bezüglich der Benachrichtigung löste beim Projektmanager Unverständnis aus, da genau dieser Vorschlag dem Kunden bei TSM2 gemacht wurde und auf Ablehnung traf. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Zum Abschluss des Meetings teilte der Kunde nochmals seine Annerkennung und Dankbarkeit lautstark mit dem Projektmanager. Der Kunde schien über das bisherige System sehr glücklich zu sein.
```suggestion
Zum Abschluss des Meetings teilte der Kunde nochmals seine Anerkennung und Dankbarkeit lautstark mit dem Projektmanager. Der Kunde schien über das bisherige System sehr glücklich zu sein. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Der "Drucken" Button bei der Wochenplanansicht und der "Experiment Hinzufügen" Button bei dem Journal wurden erfolgreich implementiert.
```suggestion
Der "Drucken" Button bei der Wochenplanansicht und der "Experiment Hinzufügen" Button beim Bearbeiten einer Vorlesung wurden erfolgreich implementiert. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die Vorführung der Buttons und des optimierten Gerätefelds wurden von dem Kunden erfreut angenommen. Allerdings wurden von Ihm noch einige Änderungen gewünscht. Die meisten davon waren visuller Natur
```suggestion
Die Vorführung der Buttons und des optimierten Gerätefelds wurden von dem Kunden erfreut angenommen. Allerdings wurden von Ihm noch einige Änderungen gewünscht. Die meisten davon waren visueller Natur, wie die Umbenennung und Umfärbung von Buttons. Eine jedoch war direkt so groß, dass der Projektmanager sie direkt im Meeting als out-of-Scope deklarieren konnte. Der Kunde forderte noch die Einführung einer zusätzlichen Rolle, die des Assistenten. Eine genaue Auflistung der Forderungen findet man in der Vision. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Auch wurde hier geich die Auslieferung und deren Ablauf mit dem Kunden besprochen. Der Kunde war mit den Abläufen einverstanden. Die Installation wurde auf den 28-06 und den 29.06.2021 festgelegt. De
```suggestion
Auch wurde hier gleich die Auslieferung und deren Ablauf mit dem Kunden besprochen. Der Kunde war mit den Abläufen einverstanden. Die Installation wurde auf den 28.06. und den 29.06.2021 festgelegt. Der Ausliefertermin sollte am 01.07.2021 stattfinden. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +* Installation auf das Produktivsystem war für den 28.7.2021 geplant und sollte nicht verschoben werden
```suggestion
* Installation auf das Produktivsystem war für den 28.06.2021 geplant und sollte nicht verschoben werden 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Beim Treffen am 23.07.2021 teilte uns der Kunde mit, dass er zahlreiche Änderungen wünscht. So sollten mehrere Buttons umbenannt sowie farblich und in der Form verändert werden. Außerdem wünschte er
```suggestion
Beim Treffen am 23.06.2021 teilte uns der Kunde mit, dass er zahlreiche Änderungen wünscht. So sollten mehrere Buttons umbenannt sowie farblich und in der Form verändert werden. Außerdem wünschte er sich eine zusätzliche Rolle und die Programmlogik sollte auch an einer Stelle geändert werden. Darüber hinaus zum Umfang dieser Änderungen waren Benennungswünsche widersprüchlich zur Funktionalität der Buttons. Nach längerer Beratung entschieden wir uns, diese Änderungswünsche abzulehnen und diese in der Zukunftsvision zu dokumentieren. Wir begründeten diese Entscheidung mit folgenden Argumenten:
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Alle vom Wunsch betroffenen Teile wurden dem Kunden vorher mehrmals gezeigt und von ihm bestätigt. So waren alle z.B. alle Bezeichnungen bereits in den vorgelegten Wireframes enthalten. Auch beim dem
```suggestion
Alle vom Wunsch betroffenen Teile wurden dem Kunden vorher mehrmals gezeigt und von ihm bestätigt. So waren z.B. alle Bezeichnungen bereits in den vorgelegten Wireframes enthalten. Auch bei den vom Kunden durchgeführten Usertests hätte er diese Wünsche äußern können. Das Aufkommen eines solchen Änderungswunsches 2 Werktage vor dem Aufspielen auf das Livesystem zeigt aber auch, dass es uns trotz intensiven Bemühungen nicht gelungen ist, dem Kunden unser Arbeitsweise so zu erläutern das er sie ausreichend verstanden hat. Über die gesamte Dauer des Projekts haben wir die Beobachtung gemacht, dass der Kunde Änderungen in Bereichen wünscht die er bereits abgenommen hatte, die Priorisierung von Abschnitten anpassen möchte und Vorschlägen, Beratungen und Erklärungen von uns kaum Beachtung schenkt.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die Auswerung hat ergeben, dass Frau Dr. Krawietz mit den von uns gestellten Aufgaben, sehr gut zurecht kam und Ihr auch keine Fehler aufgefallen sind. Wir sehen uns hier bestätigt, dass wir die gefo
```suggestion
Die Auswertung hat ergeben, dass Frau Dr. Krawietz mit den von uns gestellten Aufgaben, sehr gut zurecht kam und Ihr auch keine Fehler aufgefallen sind. Wir sehen uns hier bestätigt, dass wir die geforderte intuitive Arbeitsweise auf dem System erreichen konnten, da Frau Dr. Krawietz keine Hilfestellung hatte und auch keinen Zugriff auf eine Anwenderdokumentation. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Diese Ziel wurde erreicht, es ist nun mit unserem System möglich eine komplette Vorlesung, mit dem Studiengang, einem optionalen Titel, dem Datum, der Uhrzeit und den entsprechenden Experimenten, die
```suggestion
Diese Ziel wurde erreicht. Es ist nun mit unserem System möglich eine komplette Vorlesung, mit dem Studiengang, einem optionalen Titel, dem Datum, der Uhrzeit und den entsprechenden Experimenten, die in der Vorlesung vorgeführt werden sollen, zu planen und zu buchen. Dies wurde erreicht mit Hilfe der *Voreinstellung*, welche die Kerndaten der Vorlesung, wie Studiengang, optionaler Titel, Datum und Uhrzeit festlegen. Die Auswahl der Experimente erfolgt über ein Icon in der Experimenteübersicht, in dem man durch Klicken auf ein Einkaufswagensymbol Experimente zur Vorlesung hinzufügen oder abwählen kann. Beim Buchungsabschluss wird dem Nutzer eine Übersicht der ausgewählten Experimente im *Warenkorb* angezeigt, wo er nun auch die Reihenfolge der Experimente verändern kann. Zusätzlich kann er bei Bedarf auch einen Kommentar pro Vorlesung hinterlassen.  
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Auch dieses Ziel wurde erreicht und wird von uns durch das *Journal* umgesetzt. Hier kann sich der Dozent alle bisher gebuchten Vorlesungen ansehen und diese, wenn die Vorlesung noch nicht gehalten w
```suggestion
Auch dieses Ziel wurde erreicht und wird von uns durch das *Journal* umgesetzt. Hier kann sich der Dozent alle bisher gebuchten Vorlesungen ansehen und diese, wenn die Vorlesung noch nicht gehalten wurde, verändern. Hier können Experimente hinzugefügt werden oder aus der Buchung gelöscht werden. Auch lässt sich hier auch die Reihenfolge der Experimente und der Kommentar bearbeiten. Die gesamte Buchung kann auch gelöscht werden. Löschen und Bearbeiten einer Buchung ist nur möglich wenn sie noch in der Zukunft liegt.
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Ein weiteres Ziel, dass wir durch die *Dozentenwoche* erreichen konnten, bestand in einer strukturierten Darstellung der Buchungen. Durch klicken auf die Dozentenwoche, kann der Dozent sich nach Ausw
```suggestion
Ein weiteres Ziel, dass wir durch die *Dozentenwoche* erreichen konnten, bestand in einer strukturierten Darstellung der Buchungen. Durch Klicken auf die Dozentenwoche, kann der Dozent sich nach Auswahl des Jahrs und der Kalenderwoche eine Wochenplanübersicht erstellen lassen. Diese wird dann online angezeigt und kann über die Druckfunktion des Browsers gedruckt oder als PDF generiert werden. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Ziel erreicht durch den *Login*. Durch unterschiedliche Userrollen ist es möglich, die Nutzer mit ihren unterschiedlichen Funktionen und Rechten voneinander zu trennen. Auch wird es so ermöglicht, da
```suggestion
Ziel erreicht durch den *Login*. Durch unterschiedliche Userrollen ist es möglich, die Nutzer mit ihren unterschiedlichen Funktionen und Rechten voneinander zu trennen. Auch wird es so ermöglicht, dass der Admin keine Vorlesungen der Dozenten bearbeiten kann, oder die Dozenten Vorlesungen anderer Dozenten verändern können. Weiterhin hat der Admin auf alle Funktionen Zugriff, die der Experimentebearbeitung oder allgemeinen Systemverwaltung (Nutzerverwaltung etc.) entsprechen. Der Login wurde von uns nicht selbst erstellt, sondern wir verwendeten die vorhandene Nutzerverwaltung des Systems. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Wir hatten nicht genug Zeit alle Ziele zu erfüllen. Dadurch, dass zwei Teammitglieder uns am Anfang des Semesters verlassen haben und uns nur ein neues Teammitglied hinzugefügt wurde, fehlte uns die
```suggestion
Wir hatten nicht genug Zeit alle Ziele zu erfüllen. Dadurch, dass zwei Teammitglieder uns am Anfang des Semesters verlassen haben und uns nur ein neues Teammitglied hinzugefügt wurde, fehlte uns die komplette Arbeitskraft eines Teammitglieds über das Semester. Auch die Einarbeitungszeit des neuen Mitglieds konnte nicht produktiv für das Projekt genutzt werden. Auch die vielen Änderungen des Kunden, behinderten uns stark am eigentlichen Arbeiten an der Aufgabe, da eigentlich beschlossene Aufgaben immer wieder neu analysiert und dokumentiert werden mussten. Auch die Korrektur des Belegs am Anfang des Semesters kostete viel Arbeitszeit, die aber für das System keine Fortschritte gebracht hat. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Bei dem Projekt in SE gab es für mich einige Höhen und einige Tiefen. Ich durfte durch das Projekt, einige tolle Bekanntschaften machen und auch den Lehrkörper aus einer anderen Perspektive kennenler
```suggestion
Bei dem Projekt in SE gab es für mich einige Höhen und einige Tiefen. Ich durfte durch das Projekt, einige tolle Bekanntschaften machen und auch den Lehrkörper aus einer anderen Perspektive kennenlernen. Zum Beispiel wurde mir erst hier bewusst, dass es auch an unserer Hochschule einige Menschen gibt, die sich gegen Veränderung sträuben und es ein harter Kampf sein kann, neue Systeme in den Arbeitsalltag zu integrieren. Diese Erfahrung machte ich so zum ersten Mal und dachte bis jetzt immer, diese typischen Aussagen wie „aber früher war alles besser“, würden sich auf mein Berufsleben begrenzen. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Zu guter Letzt möchte ich noch ein paar loben Worte an mein Team richten. Ich durfte lernen wie wichtig es ist, ein Team zu haben mit dem man wirklich gut und eifrig zusammenarbeiten kann. Wie wichti
```suggestion
Zu guter Letzt möchte ich noch ein paar lobende Worte an mein Team richten. Ich durfte lernen wie wichtig es ist, ein Team zu haben mit dem man wirklich gut und eifrig zusammenarbeiten kann. Wie wichtig es ist, dass man sich auf Absprachen verlassen kann oder wenn Fehler passieren, man nicht damit beschäftigt ist einen Schuldigen zu finden, sondern wie man das Problem lösen kann. Ein Team bei dem man ehrlich sein kann und auch mal gemaßregelt wird, wenn etwas über die Stränge schlägt. Bei Problemen der anderen Teams, habe ich oft gehört „ja, die anderen“, deshalb bin ich so froh, dass bei meinem Team alles seit der ersten Minute auf der menschlichen Seite funktioniert hat. Das Einzige was ich bedauere ist nur, dass ich durch Corona noch nie einem der anderen, die mich nun seit fast einem Jahr begleiten wirklich ins Gesicht sehen konnte. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> +Ja ich bin stolz auf das, was wir erreicht haben. Ich bin stolz darauf, das wir fast alle Hürden und Problem erfolgreich meistern konnten und ich bin stolz drauf was ich lernen konnte und auch darauf
```suggestion
Ja ich bin stolz auf das, was wir erreicht haben. Ich bin stolz darauf, dass wir fast alle Hürden und Probleme erfolgreich meistern konnten und ich bin stolz drauf was ich lernen konnte und auch darauf, dass ich für das Projekt viel einbringen konnte und durfte. 
```

2021-06-30 12:37 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Ergebnisse.adoc
> + Des Weiteren fällt mir auf, dass sich mein entwicklungsbezogener Kenntnisstand gefestigt und erweitert hat. Durch den konstanten Austausch mit Teammitgliedern mit erhöhter Expertise wurde mir viel ü
```suggestion
Des Weiteren fällt mir auf, dass sich mein entwicklungsbezogener Kenntnisstand gefestigt und erweitert hat. Durch den konstanten Austausch mit Teammitgliedern mit erhöhter Expertise wurde mir viel über Architektur, Konventionen und sämtliche Methoden vermittelt, vom Testing bis hin zum Qualitätsmanagement. Auch habe ich eine neue Programmiersprache (Ruby) und das verwendete Framework (Ruby on Rails) kennengelernt, sodass meine Einarbeitungsaufwand für das eventuelle Nutzen dieser Sprache verringert wurde, parallel zur gestiegenen Neugier. 
```

2021-07-01 15:43 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die Problematik das Textfelder bei dem Experimentefeld Gefahren übereinander geschoben werden wurde behoben. Hiermit endete die Weiterentwicklung am System und wir konnten den *IOC-Meilenstein* absch
```suggestion
Die Problematik, dass Textfelder bei dem Experimentefeld "Gefahren" übereinander geschoben werden, wurde behoben. Hiermit endete die Weiterentwicklung am System und wir konnten den *IOC-Meilenstein* abschließen. 
```

2021-07-01 15:43 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +Die Auslieferung fand am 01.07.2021 in der HTW Z254 auf dem persönlichen Rechner des Kunden statt. Das Abgabeprotokoll wurde im Vorfeld dem Kunden per Mail geschickt und so von Ihm akzeptiert. Die vo
```suggestion
Die Auslieferung fand am 01.07.2021 in der HTW Z254 auf dem persönlichen Rechner des Kunden statt. Das Abgabeprotokoll wurde im Vorfeld dem Kunden per Mail geschickt und so von Ihm akzeptiert. Die vorbereiteten Szenarien wurden alle vom Kunden persönlich durchgeführt und liefen fehlerfrei durch. Es wurden keine Anmerkungen vom Kunden gemacht. Zusätzlich zu den Dokumentationen wurde dem Kunden ein Teil der Vision übergeben, dessen Inhalt sich um die Zukunftsanforderungen und die noch umzusetzenden Änderungen bezog. Hintergrund hier war, dass wenn der Kunden das Projekt in Zukunft nochmals optimieren möchte, er hier eine Zusammenfassung seiner Wünsche zur Verfügung hätte. 
```

2021-07-01 15:43 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Als das Projekt endgültig beim Kunden abgegeben war, waren wir alle sehr erleichert und glücklich. Ein großes Projekt mit sehr viel Nervenaufwand und Arbeitszeit ging nun zu Ende. Auch über das An
```suggestion
** Als das Projekt endgültig beim Kunden abgegeben war, waren wir alle sehr erleichtert und glücklich. Ein großes Projekt mit sehr viel Nervenaufwand und Arbeitszeit ging nun zu Ende. Auch über das Angebot des Kunden, dass es vielleicht möglich sei nächstes Semester das Projekt als studentische Hilfskraft fortzuführen, sahen wir als große Bestätigung des Kunden unsere Arbeit gegenüber. 
```

2021-07-01 15:43 UTC, richardboehme commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Das Inkrement so spät durchzuführen hat sich als Fehler erwiesen. Wir waren uns zwar sicher, dass wir mit den Wireframes und der Vorführung die endgültige Zustimmung des Kunden erreicht hätte, dem
```suggestion
** Das erste Inkrement so spät durchzuführen hat sich als Fehler erwiesen. Wir waren uns zwar sicher, dass wir mit den Wireframes und der Vorführung die endgültige Zustimmung des Kunden erreicht hätten, dem war aber leider nicht so. Wir mussten leider feststellen, dass dem Kunden, als er sich mit der Software allein beschäftigte, nochmals Änderungswünsche eingefallen sind. In dieser Situation wäre es sicher besser gewesen, mit dem Kunden viele kleine Inkremente durchzuführen. 
```

2021-07-01 17:27 UTC, s80523 approved these changes

2021-07-01 17:27 UTC, s80523 commented on Dokumentationen/Projekt Bericht/Durchführung.adoc
> +** Das erste Inkrement so spät durchzuführen hat sich als Fehler erwiesen. Wir waren uns zwar sicher, dass wir mit den Wireframes und der Vorführung die endgültige Zustimmung des Kunden erreicht hätt
```suggestion
** Das erste Inkrement so spät durchzuführen hat sich als Fehler erwiesen. Wir waren uns zwar sicher, dass wir mit den Wireframes und der Vorführung die endgültige Zustimmung des Kunden erreicht hatten, dem war aber leider nicht so. Wir mussten leider feststellen, dass dem Kunden, als er sich mit der Software allein beschäftigte, nochmals Änderungswünsche eingefallen sind. In dieser Situation wäre es sicher besser gewesen, mit dem Kunden viele kleine Inkremente durchzuführen. 
```

2021-07-01 17:27 UTC, merged