added future requirements to vision
Schmiddl99/experimenteverwaltung-i2 pull request #261
Opened 2021-06-16 12:13 UTC by s80523

Ich denke, dass wir diese Zukunftsanforderungen auch auf jeden Fall nochmal irgendwo im Projektbericht erwähnen sollten, um die Gründe (geänderte Priorisierung etc.) deutlich zu machen. Wenn sie nur am Ende der Vision stehen, gehen sie wahrscheinlich unter. 

closes #254

2021-06-16 14:36 UTC, Greyhound993 approved these changes
Danke für die schnelle Arbeit

2021-06-16 15:02 UTC, richardboehme requested changes
Sieht gut aus! Hatten wir nicht noch andere "Zukunftsvisionen" oder irre ich mich da?

2021-06-16 15:02 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +* im Jorunal soll es möglich werden, explizite Buchungen anhand einer Filterfunktion zu finden
```suggestion
* im Journal soll es möglich werden, explizite Buchungen anhand einer Filterfunktion zu finden 
```

2021-06-17 14:35 UTC, s80523 commented
> Sieht gut aus! Hatten wir nicht noch andere "Zukunftsvisionen" oder irre ich mich da?

@Greyhound993 @pigutsche fällt euch noch was ein? 

oder meinst du das, was wir schon in SE1 festgelegt hatten? @richardboehme

2021-06-17 15:20 UTC, richardboehme approved these changes
> > Sieht gut aus! Hatten wir nicht noch andere "Zukunftsvisionen" oder irre ich mich da?
> 
> @Greyhound993 @pigutsche fällt euch noch was ein?
> 
> oder meinst du das, was wir schon in SE1 festgelegt hatten? @richardboehme

Ne meinte aus SE I aber sehe gerade, dass das was du geschrieben hast nur ein Unterpunkt von den anderen Zukunftsaussichten ist also sollte es passen

2021-06-17 15:22 UTC, merged