Finished User doc
Schmiddl99/experimenteverwaltung-i2 pull request #270
Opened 2021-06-24 15:45 UTC by s80523

Es ist nicht schön, aber erfüllt seinen Zweck. Ich habe sehr auf Rechtschreibung etc. geachtet und hab sogar nochmal alles überflogen, ihr müsstet also nicht zu gründlich lesen, auch wenn ich evtl. etwas übersehen habe. Wichtiger wäre es zu wissen, ob ich etwas vergessen habe oder anders machen soll.

2021-06-25 14:57 UTC, richardboehme requested changes
Hab doch ein bisschen genauer drüber gelesen und ein paar Fehler korrigiert. Zudem denke ich wir sollten bei den Dozenten noch erwähnen, dass Buchungen in der Vergangenheit nicht bearbeitet/gelöscht werden können. Ansonsten sollte aber alles drin sein!

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Das Ziel dieses Dokuments ist es, eine Art Handbuch bezüglich der Nutzung des weiterentwickleten Experiemente-Management-Systems bereit zu stellen. Die Anleitungen beziehen sich detailiert und anscha
```suggestion
Das Ziel dieses Dokuments ist es, eine Art Handbuch bezüglich der Nutzung des weiterentwickelten Experimente-Management-Systems bereit zu stellen. Die Anleitungen beziehen sich detailliert und anschaulich auf die neuen Anwendungsfälle und werden dabei anhand der unterschiedlichen Nutzerrollen strukturiert. Der Zweck dieser Anwenderdokumentation ist es, dem Nutzer bei Fragen und Unklarheiten spezifische Hilfeleistungen bereitzustellen. Dabei wird großteils auf die Veranschaulichung durch Screenshots gesetzt. Der Anwender soll im Fall von Orientierungslosigkeit in der Lage sein, sich anhand dieses Dokuments selber zu helfen, um Kommunikations- und Zeitaufwand für den Nutzer selbst und das Entwicklerteam zu sparen. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Der Nutzen des weiterentwickelten EMS liegt nun nicht mehr nur in der Informationsbeschaffung, sondern auch in der Planung. Dozenten ist es nun möglich, die benötigten Experimente ohne Mailverkehr zu
Ich würde den letzten Satz ein bisschen umformulieren:
```suggestion
Der Nutzen des weiterentwickelten EMS liegt nun nicht mehr nur in der Informationsbeschaffung, sondern auch in der Planung. Dozenten ist es nun möglich, die benötigten Experimente ohne Mailverkehr zu "buchen". Durch eben diese Buchungen wird es dem Kunden möglich, die Termine der Bereitstellung der Experimente übersichtlich und einheitlich einzusehen. Das System generiert automatisiert Wochenpläne, die gedruckt werden können, um die Buchungsübersicht zu Papier zu bringen.  Bei Änderungen muss kein direkter Kontakt mehr aufgenommen werden, da Anwender mit Dozentenrolle ihre Buchungen im Journal überarbeiten können. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Der Grundbaufbau des Systems ist der selbe geblieben, wie bei der Altversion. Auf der Startseite ist es möglich, sich durch die Experimenmtekategorien und somit auch durch die Experimente zu klicken
```suggestion
Der Grundaufbau des Systems ist der selbe geblieben, wie bei der Altversion. Auf der Startseite ist es möglich, sich durch die Experimentekategorien und somit auch durch die Experimente zu klicken oder sie zu suchen. Durch Klicken auf die Rollenbezeichnung öffnet sich eine Funktionsübersicht in Form eines Auswahlmenüs. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +NOTE: Die Druckkonvertierung der Dozentwoche ist für alle gängigen Browser, die auf der Chromium Enginge laufen optimiert. Es ist daher zu empfehlen bspw. Chrome für den Druckvorgang zu nutzen. Bei V
```suggestion
NOTE: Die Druckkonvertierung der Dozentenwoche ist für alle gängigen Browser, die auf der Chromium Engine laufen optimiert. Es ist daher zu empfehlen bspw. Chrome für den Druckvorgang zu nutzen. Bei Verwendung von anderen Browsern kann es ungeklärt zu minimalen Fehlern kommen, die jedoch keine Auswirkung auf die semantische oder syntaktische Korrektheit des Dokuments haben. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Um auf die Kontenübersicht zu gelange, muss der Admin im Auswahlmenü auf "Kontenübersicht" klicken.
```suggestion
Um auf die Kontenübersicht zu gelangen, muss der Admin im Auswahlmenü auf "Kontenübersicht" klicken. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Nachdem alle Angaben ordnungsgemäß getätigt wurde, kann das Konto durch Druck auf "Speichern" angelegt werden. Es ist nun in der Übersicht zu finden.
```suggestion
Nachdem alle Angaben ordnungsgemäß getätigt wurden, kann das Konto durch Druck auf "Speichern" angelegt werden. Es ist nun in der Übersicht zu finden. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Es öffnet sich das ausgefülltes Nutzerformular, (siehe <<Nutzer anlegen, Nutzer anlegen>>) wo die Angaben erneut bearbeitet werden können. Durch Druck auf "Speichern" werden die Änderungen übernommen
```suggestion
Es öffnet sich das ausgefüllte Nutzerformular, (siehe <<Nutzer anlegen, Nutzer anlegen>>) wo die Angaben erneut bearbeitet werden können. Durch Druck auf "Speichern" werden die Änderungen übernommen. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Als nächstes muss ein Zukunftsdatum als Termin ausgewählt werden.
"Zukunftsdatum" klingt bisschen komisch oder? Vielleicht lieber so?
```suggestion
Als nächstes muss ein Datum in der Zukunft als Termin ausgewählt werden. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Nun befindet der Dozent sich auf der Experimenteüberischt. Hier kann er sich durch die Kategorien navigieren. Ab diesem Schritt ist es außerdem möglich ein benutzerdefiniertes Experimente buchungsint
```suggestion
Nun befindet der Dozent sich auf der Experimenteüberischt. Hier kann er sich durch die Kategorien navigieren. Ab diesem Schritt ist es außerdem möglich ein benutzerdefiniertes Experiment buchungsintern anzulegen. Der Nutzer kann die Buchung außerdem jederzeit abbrechen. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Wenn das gewünschte Experiment gefunden wurde, kann es mit einem Druck auzf was Warenkorb-Symbol selektiert werden.
```suggestion
Wenn das gewünschte Experiment gefunden wurde, kann es mit einem Druck auf was Warenkorb-Symbol selektiert werden. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Um ein Manuellexperiment zum Warenkorb hinzuzufügen, muss der Knopf "Manuell Experiment hinzufügen" gedrückt werden.
```suggestion
Um ein benutzerdefiniertes Experiment zum Warenkorb hinzuzufügen, muss der Knopf "Manuell Experiment hinzufügen" gedrückt werden.
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Wenn der Nutzer mit seiner Auswahl zufrieden ist, kann er durch Druck auf "Zum Buchungsabschluss" in die Warenkorbüberischt gelangen.
```suggestion
Wenn der Nutzer mit seiner Auswahl zufrieden ist, kann er durch Druck auf "Zum Buchungsabschluss" in die Warenkorbübericht gelangen. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +In dieser Übersicht ist es möglich, die Buchung final zu bearbeiten. Durch Druck auf "Zurück" gelant der Dozent wieder zur Experimenteübersicht um dort die Experimenteselektion anzupassen. Mithilfe d
```suggestion
In dieser Übersicht ist es möglich, die Buchung final zu bearbeiten. Durch Druck auf "Zurück" gelangt der Dozent wieder zur Experimenteübersicht um dort die Experimenteselektion anzupassen. Mithilfe der Mülleimer-Symbole können Experimente durch Klick aus der Buchung entfernt werden. Für Zusatzinformationen bietet das Kommentarfeld Platz. Die Reihenfolge der Experimente kann per Drag-and-Drop (gedrückt halten und ziehen) mithilfe der Dreistrich-Symbole geändert werden. Wenn alle Anpassungen stimmig sind, müssen die Änderungen durch Druck auf "Änderungen übernehmen" gespeichert werden, um sie bei möglichem Neuladen der Seite nicht zu verlieren. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Um dies zu erreichen, muss das Journal durch Druck auf "Journal" im Auswahlmenü klickt.
```suggestion
Um dies zu erreichen, muss das Journal durch Druck auf "Journal" im Auswahlmenü aufgerufen werden. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +In der Journalüberischt werden die Buchungen (wenn vorhanden) aufgelistet. Manche Buchungsdetails werden dabei vorerst nicht aufgelistet. Durch Druck auf die gwünschte Buchung werden alle Information
```suggestion
In der Journalübersicht werden die Buchungen (wenn vorhanden) aufgelistet. Manche Buchungsdetails werden dabei vorerst nicht aufgelistet. Durch Druck auf die gewünschte Buchung werden alle Informationen angezeigt. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Nachdem die Buchung "aufgeklappt" wurde, sind nun auch die Experimente und der Kommentar sichtbar. Des Weiteren besteht auf der Journalbersicht die Möglichkeit, eine Buchung zu löschen (Druck auf das
```suggestion
Nachdem die Buchung "aufgeklappt" wurde, sind nun auch die Experimente und der Kommentar sichtbar. Des Weiteren besteht auf der Journalübersicht die Möglichkeit, eine Buchung zu löschen (Druck auf das Eimer-Symbol) oder zu bearbeiten (Druck auf das Stift-Symbol.) Wenn eine Buchung gelöscht werden soll, wird der Nutzer gezwungen, dies zu bestätigen, um unbeabsichtigte Löschungen zu vermeiden. 
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Die Bearbeitung der Buchung verhält sich ähnlich, wie der Warenkorb beim Anlegen einer Buchung. Es ist möglich Experimente hinzuzufügen oder zu Entfernen, die Reihenfolge zu ändern, die Änderungen zu
```suggestion
Die Bearbeitung der Buchung verhält sich ähnlich, wie der Warenkorb beim Anlegen einer Buchung. Es ist möglich Experimente hinzuzufügen oder zu Entfernen, die Reihenfolge zu ändern, die Änderungen zu speichern und die Buchung zu persistieren oder die Bearbeitung wieder abzubrechen und die Änderungen zu verwerfen. Die Voreinstellungen können nicht geändert werden. Wenn dies trotzdem notwendig ist, muss die Buchung gelöscht und eine neue angelegt werden.
```

2021-06-25 14:57 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +NOTE: Die Druckkonvertierung der Dozentwoche ist für alle gängigen Browser, die auf der Chromium Enginge laufen optimiert. Es ist daher zu empfehlen bspw. Chrome für den Druckvorgang zu nutzen. Bei V
```suggestion
NOTE: Die Druckkonvertierung der Dozentenwoche ist für alle gängigen Browser, die auf der Chromium Engine laufen optimiert. Es ist daher zu empfehlen bspw. Chrome für den Druckvorgang zu nutzen. Bei Verwendung von anderen Browsern kann es ungeklärt zu minimalen Fehlern kommen, die jedoch keine Auswirkung auf die semantische oder syntaktische Korrektheit des Dokuments haben. 
```

2021-06-26 13:18 UTC, s80523 commented
> Hab doch ein bisschen genauer drüber gelesen und ein paar Fehler korrigiert. Zudem denke ich wir sollten bei den Dozenten noch erwähnen, dass Buchungen in der Vergangenheit nicht bearbeitet/gelöscht werden können. Ansonsten sollte aber alles drin sein!

Nevermind, zum Glück hast du doch nochmal gründlich drüber geschaut. Danke dir! 🤣
Dass nicht rückwärts bearbeitet/gelöscht werden kann, schreibe ich noch bim Bearbeiten als Note dazu!

2021-06-26 21:49 UTC, richardboehme approved these changes
Ganz kleiner Typo ist mir hier noch aufgefallen. Ansonsten kann das so germerged werden! 😄

2021-06-26 21:49 UTC, richardboehme commented on Dokumentationen/se2_documentations/Anwenderdokumentation.adoc
> +Nachdem die Buchung "aufgeklappt" wurde, sind nun auch die Experimente und der Kommentar sichtbar. Des Weiteren besteht auf der Journalübersicht die Möglichkeit, eine Buchung zu löschen (Druck auf da
```suggestion
Nachdem die Buchung "aufgeklappt" wurde, sind nun auch die Experimente und der Kommentar sichtbar. Des Weiteren besteht auf der Journalübersicht die Möglichkeit, eine Buchung zu löschen (Druck auf das Eimer-Symbol) oder zu bearbeiten (Druck auf das Stift-Symbol). Wenn eine Buchung gelöscht werden soll, wird der Nutzer gezwungen, dies zu bestätigen, um unbeabsichtigte Löschungen zu vermeiden.
```

2021-06-28 19:28 UTC, Greyhound993 approved these changes
Finde ich sehr gut gemacht und geschrieben, nicht zu förmlich und auch nicht zu locker. Ich glaube dass die doku gut ankommt :)

2021-06-29 07:37 UTC, merged