added last future visions
Schmiddl99/experimenteverwaltung-i2 pull request #273
Opened 2021-06-30 08:20 UTC by s80523

2021-06-30 10:44 UTC, richardboehme requested changes

2021-06-30 10:44 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +** "Buchung abrrechen"-Button soll rot werden
```suggestion
** "Buchung abbrechen"-Button soll rot werden
```

2021-06-30 10:44 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +** einheitliche Größe der drei Side Bar Buttons während einer Buchung umsetzen
```suggestion
** einheitliche Größe der drei Sidebar-Buttons während einer Buchung umsetzen
```

2021-06-30 10:44 UTC, richardboehme commented on Dokumentationen/requirements/vision.adoc
> +* bei Zeitraumauswahl für die Dozentenwochenansicht soll standardmäißg die nächste Kalenderwoche angezeigt werden
```suggestion
* bei Zeitraumauswahl für die Dozentenwochenansicht soll standardmäßig die nächste Kalenderwoche angezeigt werden
```

2021-06-30 11:49 UTC, Greyhound993 requested changes
Alles super wenn die Rf, draußen sind, es fehlt aber eine Änderung: 
Wenn man sich im Buchungsprozess befindet, soll in der Detailansicht (wenn man ein Experiment nicht auswählt sondern anklickt) der Button "Karteikarte öffnen" ausgeblendet werden

2021-07-01 09:03 UTC, richardboehme approved these changes

2021-07-01 15:38 UTC, merged