Anpassungen der SWRs
Schmiddl99/experimenteverwaltung-i2 pull request #97
Opened 2021-01-08 15:43 UTC by s80523

**Anmerkungen:**
-  Wir haben die SWFAs relativ UC-frei gemacht (bis auf SWFA 1 evtl.) und in der Mail erwähnte Kleinigkeiten ergänzt.
  -> Allgemeine Notwendigkeiten 
  -> wenig Details 

- **Geklärt werden muss noch:**
-  entfallene Details müssen noch in den UCs untergebracht werden (oder nicht?)
-  SOLLEN Rückwärtsbuchungen erlaubt werden?
- was ist mit Datenverschlüsselung? 
- sind Erwähnungen Bezüglich Optimierungen (Antwortzeiten und Ladezeiten etc.) überhaupt von Nöten bzw. macht uns das nicht zu viel unnötigen Aufwand? 
- Wie sieht es mit Wiederherstellbarkeit etc. aus? -> Backuproutinen oder so

closes #71

2021-01-08 20:56 UTC, TobiasK20 commented
- Habt ihr die entfallenen Details irgendwo gesammelt notiert? Dann könnten wir eine neue Aufgabe draus machen. 
- Datenverschlüsselung - vielleicht erstmal das zugehörige Risiko analysieren?
- Ich bin momentan für Aufwandsreduktion - haben wir auf Ladezeiten durch die Architektur überhaupt Einfluss? (Habe da keine Ahnung :D)
- Backuproutinen würde ich auf jeden Fall beschreiben! Hat auch CZ erwähnt.

2021-01-08 21:03 UTC, TobiasK20 requested changes

2021-01-08 21:03 UTC, TobiasK20 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +* *SWFA-10*: Das System muss das Erstellen von Anwenderzugängen durch den Admin gewährleisten.
+Verwalten?

2021-01-08 22:05 UTC, Greyhound993 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +* *SWFA-10*: Das System muss das Erstellen von Anwenderzugängen durch den Admin gewährleisten.
Ja verwalten ist besser

2021-01-08 22:08 UTC, TobiasK20 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +* *SWFA-10*: Das System muss das Erstellen von Anwenderzugängen durch den Admin gewährleisten.
Erstellen + Verwalten, würde beide schreiben

2021-01-12 16:54 UTC, Greyhound993 requested changes

2021-01-12 16:54 UTC, Greyhound993 commented on Dokumentationen/requirements/system-wide_requirements.adoc
Back Up Version schon vorhanden

2021-01-12 16:54 UTC, Greyhound993 commented on Dokumentationen/requirements/system-wide_requirements.adoc
RF

2021-01-12 16:54 UTC, Greyhound993 commented on Dokumentationen/requirements/system-wide_requirements.adoc
Die maximale Zahl an Log Ins muss gewährleistet sein, RF

2021-01-12 18:45 UTC, richardboehme commented
@s80523 Backups werden im Moment täglich von der Datenbank und den Bilddateien angelegt. Es werden allerdings immer nur die letzten 5 Backups behalten.

2021-01-18 20:49 UTC, TobiasK20 commented
Ist das dann die aktuelle Variante? Kann das bitte noch vor dem Meeting morgen gepusht werden, damit wir dran arbeiten können? :)

2021-01-18 20:49 UTC, TobiasK20 approved these changes

2021-01-19 20:30 UTC, Greyhound993 approved these changes

2021-01-20 10:01 UTC, richardboehme requested changes
Nur noch ein paar kleine Schreibfehler die ich gefunden habe

2021-01-20 10:01 UTC, richardboehme commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +*** Zur Überprüfung wird eine Testperson die Anwendung mit einem Abstand von 50cm Entfernung zum Bildschrim nutzen.
```suggestion
*** Zur Überprüfung wird eine Testperson die Anwendung mit einem Abstand von 50cm Entfernung zum Bildschirm nutzen. 
```

2021-01-21 11:39 UTC, s80523 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +** Überprüfbar wird dies durch Einfügen von Daten. Nach einem Neustart des Systems ist es notwendig, dass die Daten weiterhin vollständig sind.
Herr Z. meinte, dass die Überprüfung auch zu den TCs kann, aber ich habe es drinnen gelassen, damit wir einheitlich überall, wo es nötig ist, wenigstens den Ansatz stehen haben.

2021-01-21 15:43 UTC, richardboehme approved these changes

2021-01-22 10:16 UTC, TobiasK20 approved these changes

2021-01-22 10:16 UTC, TobiasK20 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +** Überprüfbar wird dies durch Einfügen von Daten. Nach einem Neustart des Systems ist es notwendig, dass die Daten weiterhin vollständig sind.
Ja, finde ich gut so

2021-01-22 10:16 UTC, TobiasK20 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +* *SWFA-3*: Das System muss Zugangsdaten der Anwender vor Diebstahl schützen.
Vielleicht noch Diebstahl "durch Dritte" oder "nicht autorisierte Personen" erläutern?

2021-01-22 12:56 UTC, s80523 commented on Dokumentationen/requirements/system-wide_requirements.adoc
> +* *SWFA-3*: Das System muss Zugangsdaten der Anwender vor Diebstahl schützen.
Hier würde ich persönlich bei der allgemeinen Formulierung bleiben, schließlich muss das Passwort etc. von Dozent A auch vor Diebstahl durch Dozent B beschützt werden und, dass Diebstahl durch nicht autorisierte Personen geschieht ist doch eindeutig oder?

2021-01-22 12:59 UTC, merged

2021-01-23 15:12 UTC, TobiasK20 commented
Habe noch was: Unter Performance müsste die Klassifizierung doch NFAP-1 heißen und nicht NFAR, oder? @s80523

2021-01-23 15:19 UTC, TobiasK20 commented
> Habe noch was: Unter Performance müsste die Klassifizierung doch NFAP-1 heißen und nicht NFAR, oder? @s80523

Hat sich erledigt